// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/source/v1/source_context.proto

package com.google.devtools.source.v1;

/**
 * <pre>
 * A CloudWorkspaceId is a unique identifier for a cloud workspace.
 * A cloud workspace is a place associated with a repo where modified files
 * can be stored before they are committed.
 * </pre>
 *
 * Protobuf type {@code google.devtools.source.v1.CloudWorkspaceId}
 */
public  final class CloudWorkspaceId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.devtools.source.v1.CloudWorkspaceId)
    CloudWorkspaceIdOrBuilder {
  // Use CloudWorkspaceId.newBuilder() to construct.
  private CloudWorkspaceId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CloudWorkspaceId() {
    name_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CloudWorkspaceId(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.devtools.source.v1.RepoId.Builder subBuilder = null;
            if (repoId_ != null) {
              subBuilder = repoId_.toBuilder();
            }
            repoId_ = input.readMessage(com.google.devtools.source.v1.RepoId.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(repoId_);
              repoId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.devtools.source.v1.SourceContextProto.internal_static_google_devtools_source_v1_CloudWorkspaceId_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.devtools.source.v1.SourceContextProto.internal_static_google_devtools_source_v1_CloudWorkspaceId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.devtools.source.v1.CloudWorkspaceId.class, com.google.devtools.source.v1.CloudWorkspaceId.Builder.class);
  }

  public static final int REPO_ID_FIELD_NUMBER = 1;
  private com.google.devtools.source.v1.RepoId repoId_;
  /**
   * <pre>
   * The ID of the repo containing the workspace.
   * </pre>
   *
   * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
   */
  public boolean hasRepoId() {
    return repoId_ != null;
  }
  /**
   * <pre>
   * The ID of the repo containing the workspace.
   * </pre>
   *
   * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
   */
  public com.google.devtools.source.v1.RepoId getRepoId() {
    return repoId_ == null ? com.google.devtools.source.v1.RepoId.getDefaultInstance() : repoId_;
  }
  /**
   * <pre>
   * The ID of the repo containing the workspace.
   * </pre>
   *
   * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
   */
  public com.google.devtools.source.v1.RepoIdOrBuilder getRepoIdOrBuilder() {
    return getRepoId();
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * The unique name of the workspace within the repo.  This is the name
   * chosen by the client in the Source API's CreateWorkspace method.
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unique name of the workspace within the repo.  This is the name
   * chosen by the client in the Source API's CreateWorkspace method.
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (repoId_ != null) {
      output.writeMessage(1, getRepoId());
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (repoId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRepoId());
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.devtools.source.v1.CloudWorkspaceId)) {
      return super.equals(obj);
    }
    com.google.devtools.source.v1.CloudWorkspaceId other = (com.google.devtools.source.v1.CloudWorkspaceId) obj;

    boolean result = true;
    result = result && (hasRepoId() == other.hasRepoId());
    if (hasRepoId()) {
      result = result && getRepoId()
          .equals(other.getRepoId());
    }
    result = result && getName()
        .equals(other.getName());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRepoId()) {
      hash = (37 * hash) + REPO_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRepoId().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.devtools.source.v1.CloudWorkspaceId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.source.v1.CloudWorkspaceId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.source.v1.CloudWorkspaceId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.source.v1.CloudWorkspaceId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.source.v1.CloudWorkspaceId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.source.v1.CloudWorkspaceId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.source.v1.CloudWorkspaceId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.devtools.source.v1.CloudWorkspaceId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.source.v1.CloudWorkspaceId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.source.v1.CloudWorkspaceId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.devtools.source.v1.CloudWorkspaceId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A CloudWorkspaceId is a unique identifier for a cloud workspace.
   * A cloud workspace is a place associated with a repo where modified files
   * can be stored before they are committed.
   * </pre>
   *
   * Protobuf type {@code google.devtools.source.v1.CloudWorkspaceId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.devtools.source.v1.CloudWorkspaceId)
      com.google.devtools.source.v1.CloudWorkspaceIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.source.v1.SourceContextProto.internal_static_google_devtools_source_v1_CloudWorkspaceId_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.source.v1.SourceContextProto.internal_static_google_devtools_source_v1_CloudWorkspaceId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.source.v1.CloudWorkspaceId.class, com.google.devtools.source.v1.CloudWorkspaceId.Builder.class);
    }

    // Construct using com.google.devtools.source.v1.CloudWorkspaceId.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (repoIdBuilder_ == null) {
        repoId_ = null;
      } else {
        repoId_ = null;
        repoIdBuilder_ = null;
      }
      name_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.devtools.source.v1.SourceContextProto.internal_static_google_devtools_source_v1_CloudWorkspaceId_descriptor;
    }

    public com.google.devtools.source.v1.CloudWorkspaceId getDefaultInstanceForType() {
      return com.google.devtools.source.v1.CloudWorkspaceId.getDefaultInstance();
    }

    public com.google.devtools.source.v1.CloudWorkspaceId build() {
      com.google.devtools.source.v1.CloudWorkspaceId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.devtools.source.v1.CloudWorkspaceId buildPartial() {
      com.google.devtools.source.v1.CloudWorkspaceId result = new com.google.devtools.source.v1.CloudWorkspaceId(this);
      if (repoIdBuilder_ == null) {
        result.repoId_ = repoId_;
      } else {
        result.repoId_ = repoIdBuilder_.build();
      }
      result.name_ = name_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.devtools.source.v1.CloudWorkspaceId) {
        return mergeFrom((com.google.devtools.source.v1.CloudWorkspaceId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.devtools.source.v1.CloudWorkspaceId other) {
      if (other == com.google.devtools.source.v1.CloudWorkspaceId.getDefaultInstance()) return this;
      if (other.hasRepoId()) {
        mergeRepoId(other.getRepoId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.devtools.source.v1.CloudWorkspaceId parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.devtools.source.v1.CloudWorkspaceId) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.devtools.source.v1.RepoId repoId_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.source.v1.RepoId, com.google.devtools.source.v1.RepoId.Builder, com.google.devtools.source.v1.RepoIdOrBuilder> repoIdBuilder_;
    /**
     * <pre>
     * The ID of the repo containing the workspace.
     * </pre>
     *
     * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
     */
    public boolean hasRepoId() {
      return repoIdBuilder_ != null || repoId_ != null;
    }
    /**
     * <pre>
     * The ID of the repo containing the workspace.
     * </pre>
     *
     * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
     */
    public com.google.devtools.source.v1.RepoId getRepoId() {
      if (repoIdBuilder_ == null) {
        return repoId_ == null ? com.google.devtools.source.v1.RepoId.getDefaultInstance() : repoId_;
      } else {
        return repoIdBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The ID of the repo containing the workspace.
     * </pre>
     *
     * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
     */
    public Builder setRepoId(com.google.devtools.source.v1.RepoId value) {
      if (repoIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        repoId_ = value;
        onChanged();
      } else {
        repoIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The ID of the repo containing the workspace.
     * </pre>
     *
     * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
     */
    public Builder setRepoId(
        com.google.devtools.source.v1.RepoId.Builder builderForValue) {
      if (repoIdBuilder_ == null) {
        repoId_ = builderForValue.build();
        onChanged();
      } else {
        repoIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The ID of the repo containing the workspace.
     * </pre>
     *
     * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
     */
    public Builder mergeRepoId(com.google.devtools.source.v1.RepoId value) {
      if (repoIdBuilder_ == null) {
        if (repoId_ != null) {
          repoId_ =
            com.google.devtools.source.v1.RepoId.newBuilder(repoId_).mergeFrom(value).buildPartial();
        } else {
          repoId_ = value;
        }
        onChanged();
      } else {
        repoIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The ID of the repo containing the workspace.
     * </pre>
     *
     * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
     */
    public Builder clearRepoId() {
      if (repoIdBuilder_ == null) {
        repoId_ = null;
        onChanged();
      } else {
        repoId_ = null;
        repoIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The ID of the repo containing the workspace.
     * </pre>
     *
     * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
     */
    public com.google.devtools.source.v1.RepoId.Builder getRepoIdBuilder() {
      
      onChanged();
      return getRepoIdFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The ID of the repo containing the workspace.
     * </pre>
     *
     * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
     */
    public com.google.devtools.source.v1.RepoIdOrBuilder getRepoIdOrBuilder() {
      if (repoIdBuilder_ != null) {
        return repoIdBuilder_.getMessageOrBuilder();
      } else {
        return repoId_ == null ?
            com.google.devtools.source.v1.RepoId.getDefaultInstance() : repoId_;
      }
    }
    /**
     * <pre>
     * The ID of the repo containing the workspace.
     * </pre>
     *
     * <code>.google.devtools.source.v1.RepoId repo_id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.source.v1.RepoId, com.google.devtools.source.v1.RepoId.Builder, com.google.devtools.source.v1.RepoIdOrBuilder> 
        getRepoIdFieldBuilder() {
      if (repoIdBuilder_ == null) {
        repoIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.devtools.source.v1.RepoId, com.google.devtools.source.v1.RepoId.Builder, com.google.devtools.source.v1.RepoIdOrBuilder>(
                getRepoId(),
                getParentForChildren(),
                isClean());
        repoId_ = null;
      }
      return repoIdBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The unique name of the workspace within the repo.  This is the name
     * chosen by the client in the Source API's CreateWorkspace method.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unique name of the workspace within the repo.  This is the name
     * chosen by the client in the Source API's CreateWorkspace method.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unique name of the workspace within the repo.  This is the name
     * chosen by the client in the Source API's CreateWorkspace method.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique name of the workspace within the repo.  This is the name
     * chosen by the client in the Source API's CreateWorkspace method.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique name of the workspace within the repo.  This is the name
     * chosen by the client in the Source API's CreateWorkspace method.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.devtools.source.v1.CloudWorkspaceId)
  }

  // @@protoc_insertion_point(class_scope:google.devtools.source.v1.CloudWorkspaceId)
  private static final com.google.devtools.source.v1.CloudWorkspaceId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.devtools.source.v1.CloudWorkspaceId();
  }

  public static com.google.devtools.source.v1.CloudWorkspaceId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CloudWorkspaceId>
      PARSER = new com.google.protobuf.AbstractParser<CloudWorkspaceId>() {
    public CloudWorkspaceId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CloudWorkspaceId(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CloudWorkspaceId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CloudWorkspaceId> getParserForType() {
    return PARSER;
  }

  public com.google.devtools.source.v1.CloudWorkspaceId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

