// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dataproc/v1/clusters.proto

package com.google.cloud.dataproc.v1;

public final class ClustersProto {
  private ClustersProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_Cluster_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_Cluster_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_ClusterConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_ClusterConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_GceClusterConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_GceClusterConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_GceClusterConfig_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_GceClusterConfig_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_InstanceGroupConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_InstanceGroupConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_ManagedGroupConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_ManagedGroupConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_DiskConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_DiskConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_NodeInitializationAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_NodeInitializationAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_ClusterStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_ClusterStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_SoftwareConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_SoftwareConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_SoftwareConfig_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_SoftwareConfig_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_CreateClusterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_CreateClusterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_UpdateClusterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_UpdateClusterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_DeleteClusterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_DeleteClusterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_GetClusterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_GetClusterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_ListClustersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_ListClustersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_ListClustersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_ListClustersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_DiagnoseClusterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_DiagnoseClusterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_dataproc_v1_DiagnoseClusterResults_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_dataproc_v1_DiagnoseClusterResults_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'google/cloud/dataproc/v1/clusters.prot" +
      "o\022\030google.cloud.dataproc.v1\032\034google/api/" +
      "annotations.proto\032)google/cloud/dataproc" +
      "/v1/operations.proto\032#google/longrunning" +
      "/operations.proto\032\036google/protobuf/durat" +
      "ion.proto\032 google/protobuf/field_mask.pr" +
      "oto\032\037google/protobuf/timestamp.proto\"\374\001\n" +
      "\007Cluster\022\022\n\nproject_id\030\001 \001(\t\022\024\n\014cluster_" +
      "name\030\002 \001(\t\0227\n\006config\030\003 \001(\0132\'.google.clou" +
      "d.dataproc.v1.ClusterConfig\0227\n\006status\030\004 ",
      "\001(\0132\'.google.cloud.dataproc.v1.ClusterSt" +
      "atus\022?\n\016status_history\030\007 \003(\0132\'.google.cl" +
      "oud.dataproc.v1.ClusterStatus\022\024\n\014cluster" +
      "_uuid\030\006 \001(\t\"\341\003\n\rClusterConfig\022\025\n\rconfig_" +
      "bucket\030\001 \001(\t\022F\n\022gce_cluster_config\030\010 \001(\013" +
      "2*.google.cloud.dataproc.v1.GceClusterCo" +
      "nfig\022D\n\rmaster_config\030\t \001(\0132-.google.clo" +
      "ud.dataproc.v1.InstanceGroupConfig\022D\n\rwo" +
      "rker_config\030\n \001(\0132-.google.cloud.datapro" +
      "c.v1.InstanceGroupConfig\022N\n\027secondary_wo",
      "rker_config\030\014 \001(\0132-.google.cloud.datapro" +
      "c.v1.InstanceGroupConfig\022A\n\017software_con" +
      "fig\030\r \001(\0132(.google.cloud.dataproc.v1.Sof" +
      "twareConfig\022R\n\026initialization_actions\030\013 " +
      "\003(\01322.google.cloud.dataproc.v1.NodeIniti" +
      "alizationAction\"\226\002\n\020GceClusterConfig\022\020\n\010" +
      "zone_uri\030\001 \001(\t\022\023\n\013network_uri\030\002 \001(\t\022\026\n\016s" +
      "ubnetwork_uri\030\006 \001(\t\022\030\n\020internal_ip_only\030" +
      "\007 \001(\010\022\036\n\026service_account_scopes\030\003 \003(\t\022\014\n" +
      "\004tags\030\004 \003(\t\022J\n\010metadata\030\005 \003(\01328.google.c",
      "loud.dataproc.v1.GceClusterConfig.Metada" +
      "taEntry\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\t:\0028\001\"\220\002\n\023InstanceGroupConfig" +
      "\022\025\n\rnum_instances\030\001 \001(\005\022\026\n\016instance_name" +
      "s\030\002 \003(\t\022\021\n\timage_uri\030\003 \001(\t\022\030\n\020machine_ty" +
      "pe_uri\030\004 \001(\t\0229\n\013disk_config\030\005 \001(\0132$.goog" +
      "le.cloud.dataproc.v1.DiskConfig\022\026\n\016is_pr" +
      "eemptible\030\006 \001(\010\022J\n\024managed_group_config\030" +
      "\007 \001(\0132,.google.cloud.dataproc.v1.Managed" +
      "GroupConfig\"Y\n\022ManagedGroupConfig\022\036\n\026ins",
      "tance_template_name\030\001 \001(\t\022#\n\033instance_gr" +
      "oup_manager_name\030\002 \001(\t\"?\n\nDiskConfig\022\031\n\021" +
      "boot_disk_size_gb\030\001 \001(\005\022\026\n\016num_local_ssd" +
      "s\030\002 \001(\005\"i\n\030NodeInitializationAction\022\027\n\017e" +
      "xecutable_file\030\001 \001(\t\0224\n\021execution_timeou" +
      "t\030\002 \001(\0132\031.google.protobuf.Duration\"\353\001\n\rC" +
      "lusterStatus\022<\n\005state\030\001 \001(\0162-.google.clo" +
      "ud.dataproc.v1.ClusterStatus.State\022\016\n\006de" +
      "tail\030\002 \001(\t\0224\n\020state_start_time\030\003 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\"V\n\005State\022\013\n\007UNK",
      "NOWN\020\000\022\014\n\010CREATING\020\001\022\013\n\007RUNNING\020\002\022\t\n\005ERR" +
      "OR\020\003\022\014\n\010DELETING\020\004\022\014\n\010UPDATING\020\005\"\250\001\n\016Sof" +
      "twareConfig\022\025\n\rimage_version\030\001 \001(\t\022L\n\npr" +
      "operties\030\002 \003(\01328.google.cloud.dataproc.v" +
      "1.SoftwareConfig.PropertiesEntry\0321\n\017Prop" +
      "ertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:" +
      "\0028\001\"n\n\024CreateClusterRequest\022\022\n\nproject_i" +
      "d\030\001 \001(\t\022\016\n\006region\030\003 \001(\t\0222\n\007cluster\030\002 \001(\013" +
      "2!.google.cloud.dataproc.v1.Cluster\"\265\001\n\024" +
      "UpdateClusterRequest\022\022\n\nproject_id\030\001 \001(\t",
      "\022\016\n\006region\030\005 \001(\t\022\024\n\014cluster_name\030\002 \001(\t\0222" +
      "\n\007cluster\030\003 \001(\0132!.google.cloud.dataproc." +
      "v1.Cluster\022/\n\013update_mask\030\004 \001(\0132\032.google" +
      ".protobuf.FieldMask\"P\n\024DeleteClusterRequ" +
      "est\022\022\n\nproject_id\030\001 \001(\t\022\016\n\006region\030\003 \001(\t\022" +
      "\024\n\014cluster_name\030\002 \001(\t\"M\n\021GetClusterReque" +
      "st\022\022\n\nproject_id\030\001 \001(\t\022\016\n\006region\030\003 \001(\t\022\024" +
      "\n\014cluster_name\030\002 \001(\t\"`\n\023ListClustersRequ" +
      "est\022\022\n\nproject_id\030\001 \001(\t\022\016\n\006region\030\004 \001(\t\022" +
      "\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t\"d",
      "\n\024ListClustersResponse\0223\n\010clusters\030\001 \003(\013" +
      "2!.google.cloud.dataproc.v1.Cluster\022\027\n\017n" +
      "ext_page_token\030\002 \001(\t\"R\n\026DiagnoseClusterR" +
      "equest\022\022\n\nproject_id\030\001 \001(\t\022\016\n\006region\030\003 \001" +
      "(\t\022\024\n\014cluster_name\030\002 \001(\t\",\n\026DiagnoseClus" +
      "terResults\022\022\n\noutput_uri\030\001 \001(\t2\262\010\n\021Clust" +
      "erController\022\244\001\n\rCreateCluster\022..google." +
      "cloud.dataproc.v1.CreateClusterRequest\032\035" +
      ".google.longrunning.Operation\"D\202\323\344\223\002>\"3/" +
      "v1/projects/{project_id}/regions/{region",
      "}/clusters:\007cluster\022\263\001\n\rUpdateCluster\022.." +
      "google.cloud.dataproc.v1.UpdateClusterRe" +
      "quest\032\035.google.longrunning.Operation\"S\202\323" +
      "\344\223\002M2B/v1/projects/{project_id}/regions/" +
      "{region}/clusters/{cluster_name}:\007cluste" +
      "r\022\252\001\n\rDeleteCluster\022..google.cloud.datap" +
      "roc.v1.DeleteClusterRequest\032\035.google.lon" +
      "grunning.Operation\"J\202\323\344\223\002D*B/v1/projects" +
      "/{project_id}/regions/{region}/clusters/" +
      "{cluster_name}\022\250\001\n\nGetCluster\022+.google.c",
      "loud.dataproc.v1.GetClusterRequest\032!.goo" +
      "gle.cloud.dataproc.v1.Cluster\"J\202\323\344\223\002D\022B/" +
      "v1/projects/{project_id}/regions/{region" +
      "}/clusters/{cluster_name}\022\252\001\n\014ListCluste" +
      "rs\022-.google.cloud.dataproc.v1.ListCluste" +
      "rsRequest\032..google.cloud.dataproc.v1.Lis" +
      "tClustersResponse\";\202\323\344\223\0025\0223/v1/projects/" +
      "{project_id}/regions/{region}/clusters\022\272" +
      "\001\n\017DiagnoseCluster\0220.google.cloud.datapr" +
      "oc.v1.DiagnoseClusterRequest\032\035.google.lo",
      "ngrunning.Operation\"V\202\323\344\223\002P\"K/v1/project" +
      "s/{project_id}/regions/{region}/clusters" +
      "/{cluster_name}:diagnose:\001*Bq\n\034com.googl" +
      "e.cloud.dataproc.v1B\rClustersProtoP\001Z@go" +
      "ogle.golang.org/genproto/googleapis/clou" +
      "d/dataproc/v1;dataprocb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.cloud.dataproc.v1.OperationsProto.getDescriptor(),
          com.google.longrunning.OperationsProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_google_cloud_dataproc_v1_Cluster_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_dataproc_v1_Cluster_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_Cluster_descriptor,
        new java.lang.String[] { "ProjectId", "ClusterName", "Config", "Status", "StatusHistory", "ClusterUuid", });
    internal_static_google_cloud_dataproc_v1_ClusterConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_dataproc_v1_ClusterConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_ClusterConfig_descriptor,
        new java.lang.String[] { "ConfigBucket", "GceClusterConfig", "MasterConfig", "WorkerConfig", "SecondaryWorkerConfig", "SoftwareConfig", "InitializationActions", });
    internal_static_google_cloud_dataproc_v1_GceClusterConfig_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_dataproc_v1_GceClusterConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_GceClusterConfig_descriptor,
        new java.lang.String[] { "ZoneUri", "NetworkUri", "SubnetworkUri", "InternalIpOnly", "ServiceAccountScopes", "Tags", "Metadata", });
    internal_static_google_cloud_dataproc_v1_GceClusterConfig_MetadataEntry_descriptor =
      internal_static_google_cloud_dataproc_v1_GceClusterConfig_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_dataproc_v1_GceClusterConfig_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_GceClusterConfig_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_dataproc_v1_InstanceGroupConfig_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_dataproc_v1_InstanceGroupConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_InstanceGroupConfig_descriptor,
        new java.lang.String[] { "NumInstances", "InstanceNames", "ImageUri", "MachineTypeUri", "DiskConfig", "IsPreemptible", "ManagedGroupConfig", });
    internal_static_google_cloud_dataproc_v1_ManagedGroupConfig_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_dataproc_v1_ManagedGroupConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_ManagedGroupConfig_descriptor,
        new java.lang.String[] { "InstanceTemplateName", "InstanceGroupManagerName", });
    internal_static_google_cloud_dataproc_v1_DiskConfig_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_dataproc_v1_DiskConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_DiskConfig_descriptor,
        new java.lang.String[] { "BootDiskSizeGb", "NumLocalSsds", });
    internal_static_google_cloud_dataproc_v1_NodeInitializationAction_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_dataproc_v1_NodeInitializationAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_NodeInitializationAction_descriptor,
        new java.lang.String[] { "ExecutableFile", "ExecutionTimeout", });
    internal_static_google_cloud_dataproc_v1_ClusterStatus_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_dataproc_v1_ClusterStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_ClusterStatus_descriptor,
        new java.lang.String[] { "State", "Detail", "StateStartTime", });
    internal_static_google_cloud_dataproc_v1_SoftwareConfig_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_dataproc_v1_SoftwareConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_SoftwareConfig_descriptor,
        new java.lang.String[] { "ImageVersion", "Properties", });
    internal_static_google_cloud_dataproc_v1_SoftwareConfig_PropertiesEntry_descriptor =
      internal_static_google_cloud_dataproc_v1_SoftwareConfig_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_dataproc_v1_SoftwareConfig_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_SoftwareConfig_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_dataproc_v1_CreateClusterRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_dataproc_v1_CreateClusterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_CreateClusterRequest_descriptor,
        new java.lang.String[] { "ProjectId", "Region", "Cluster", });
    internal_static_google_cloud_dataproc_v1_UpdateClusterRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_dataproc_v1_UpdateClusterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_UpdateClusterRequest_descriptor,
        new java.lang.String[] { "ProjectId", "Region", "ClusterName", "Cluster", "UpdateMask", });
    internal_static_google_cloud_dataproc_v1_DeleteClusterRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_dataproc_v1_DeleteClusterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_DeleteClusterRequest_descriptor,
        new java.lang.String[] { "ProjectId", "Region", "ClusterName", });
    internal_static_google_cloud_dataproc_v1_GetClusterRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_dataproc_v1_GetClusterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_GetClusterRequest_descriptor,
        new java.lang.String[] { "ProjectId", "Region", "ClusterName", });
    internal_static_google_cloud_dataproc_v1_ListClustersRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_dataproc_v1_ListClustersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_ListClustersRequest_descriptor,
        new java.lang.String[] { "ProjectId", "Region", "PageSize", "PageToken", });
    internal_static_google_cloud_dataproc_v1_ListClustersResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_dataproc_v1_ListClustersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_ListClustersResponse_descriptor,
        new java.lang.String[] { "Clusters", "NextPageToken", });
    internal_static_google_cloud_dataproc_v1_DiagnoseClusterRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_dataproc_v1_DiagnoseClusterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_DiagnoseClusterRequest_descriptor,
        new java.lang.String[] { "ProjectId", "Region", "ClusterName", });
    internal_static_google_cloud_dataproc_v1_DiagnoseClusterResults_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_dataproc_v1_DiagnoseClusterResults_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_dataproc_v1_DiagnoseClusterResults_descriptor,
        new java.lang.String[] { "OutputUri", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.cloud.dataproc.v1.OperationsProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
