// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/reads.proto

package com.google.genomics.v1;

/**
 * <pre>
 * The read group set export request.
 * </pre>
 *
 * Protobuf type {@code google.genomics.v1.ExportReadGroupSetRequest}
 */
public  final class ExportReadGroupSetRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.genomics.v1.ExportReadGroupSetRequest)
    ExportReadGroupSetRequestOrBuilder {
  // Use ExportReadGroupSetRequest.newBuilder() to construct.
  private ExportReadGroupSetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExportReadGroupSetRequest() {
    projectId_ = "";
    exportUri_ = "";
    readGroupSetId_ = "";
    referenceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ExportReadGroupSetRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            projectId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            exportUri_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            readGroupSetId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              referenceNames_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000008;
            }
            referenceNames_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        referenceNames_ = referenceNames_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.genomics.v1.ReadsProto.internal_static_google_genomics_v1_ExportReadGroupSetRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.genomics.v1.ReadsProto.internal_static_google_genomics_v1_ExportReadGroupSetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.genomics.v1.ExportReadGroupSetRequest.class, com.google.genomics.v1.ExportReadGroupSetRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PROJECT_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object projectId_;
  /**
   * <pre>
   * Required. The Google Cloud project ID that owns this
   * export. The caller must have WRITE access to this project.
   * </pre>
   *
   * <code>string project_id = 1;</code>
   */
  public java.lang.String getProjectId() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projectId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. The Google Cloud project ID that owns this
   * export. The caller must have WRITE access to this project.
   * </pre>
   *
   * <code>string project_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getProjectIdBytes() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPORT_URI_FIELD_NUMBER = 2;
  private volatile java.lang.Object exportUri_;
  /**
   * <pre>
   * Required. A Google Cloud Storage URI for the exported BAM file.
   * The currently authenticated user must have write access to the new file.
   * An error will be returned if the URI already contains data.
   * </pre>
   *
   * <code>string export_uri = 2;</code>
   */
  public java.lang.String getExportUri() {
    java.lang.Object ref = exportUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      exportUri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. A Google Cloud Storage URI for the exported BAM file.
   * The currently authenticated user must have write access to the new file.
   * An error will be returned if the URI already contains data.
   * </pre>
   *
   * <code>string export_uri = 2;</code>
   */
  public com.google.protobuf.ByteString
      getExportUriBytes() {
    java.lang.Object ref = exportUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exportUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int READ_GROUP_SET_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object readGroupSetId_;
  /**
   * <pre>
   * Required. The ID of the read group set to export. The caller must have
   * READ access to this read group set.
   * </pre>
   *
   * <code>string read_group_set_id = 3;</code>
   */
  public java.lang.String getReadGroupSetId() {
    java.lang.Object ref = readGroupSetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      readGroupSetId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. The ID of the read group set to export. The caller must have
   * READ access to this read group set.
   * </pre>
   *
   * <code>string read_group_set_id = 3;</code>
   */
  public com.google.protobuf.ByteString
      getReadGroupSetIdBytes() {
    java.lang.Object ref = readGroupSetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      readGroupSetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REFERENCE_NAMES_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList referenceNames_;
  /**
   * <pre>
   * The reference names to export. If this is not specified, all reference
   * sequences, including unmapped reads, are exported.
   * Use `*` to export only unmapped reads.
   * </pre>
   *
   * <code>repeated string reference_names = 4;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getReferenceNamesList() {
    return referenceNames_;
  }
  /**
   * <pre>
   * The reference names to export. If this is not specified, all reference
   * sequences, including unmapped reads, are exported.
   * Use `*` to export only unmapped reads.
   * </pre>
   *
   * <code>repeated string reference_names = 4;</code>
   */
  public int getReferenceNamesCount() {
    return referenceNames_.size();
  }
  /**
   * <pre>
   * The reference names to export. If this is not specified, all reference
   * sequences, including unmapped reads, are exported.
   * Use `*` to export only unmapped reads.
   * </pre>
   *
   * <code>repeated string reference_names = 4;</code>
   */
  public java.lang.String getReferenceNames(int index) {
    return referenceNames_.get(index);
  }
  /**
   * <pre>
   * The reference names to export. If this is not specified, all reference
   * sequences, including unmapped reads, are exported.
   * Use `*` to export only unmapped reads.
   * </pre>
   *
   * <code>repeated string reference_names = 4;</code>
   */
  public com.google.protobuf.ByteString
      getReferenceNamesBytes(int index) {
    return referenceNames_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getProjectIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, projectId_);
    }
    if (!getExportUriBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, exportUri_);
    }
    if (!getReadGroupSetIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, readGroupSetId_);
    }
    for (int i = 0; i < referenceNames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, referenceNames_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getProjectIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, projectId_);
    }
    if (!getExportUriBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, exportUri_);
    }
    if (!getReadGroupSetIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, readGroupSetId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < referenceNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(referenceNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReferenceNamesList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.genomics.v1.ExportReadGroupSetRequest)) {
      return super.equals(obj);
    }
    com.google.genomics.v1.ExportReadGroupSetRequest other = (com.google.genomics.v1.ExportReadGroupSetRequest) obj;

    boolean result = true;
    result = result && getProjectId()
        .equals(other.getProjectId());
    result = result && getExportUri()
        .equals(other.getExportUri());
    result = result && getReadGroupSetId()
        .equals(other.getReadGroupSetId());
    result = result && getReferenceNamesList()
        .equals(other.getReferenceNamesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROJECT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProjectId().hashCode();
    hash = (37 * hash) + EXPORT_URI_FIELD_NUMBER;
    hash = (53 * hash) + getExportUri().hashCode();
    hash = (37 * hash) + READ_GROUP_SET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReadGroupSetId().hashCode();
    if (getReferenceNamesCount() > 0) {
      hash = (37 * hash) + REFERENCE_NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getReferenceNamesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.genomics.v1.ExportReadGroupSetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.ExportReadGroupSetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.ExportReadGroupSetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.ExportReadGroupSetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.ExportReadGroupSetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.genomics.v1.ExportReadGroupSetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.genomics.v1.ExportReadGroupSetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.genomics.v1.ExportReadGroupSetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.genomics.v1.ExportReadGroupSetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.genomics.v1.ExportReadGroupSetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.genomics.v1.ExportReadGroupSetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The read group set export request.
   * </pre>
   *
   * Protobuf type {@code google.genomics.v1.ExportReadGroupSetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.genomics.v1.ExportReadGroupSetRequest)
      com.google.genomics.v1.ExportReadGroupSetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.genomics.v1.ReadsProto.internal_static_google_genomics_v1_ExportReadGroupSetRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.genomics.v1.ReadsProto.internal_static_google_genomics_v1_ExportReadGroupSetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.genomics.v1.ExportReadGroupSetRequest.class, com.google.genomics.v1.ExportReadGroupSetRequest.Builder.class);
    }

    // Construct using com.google.genomics.v1.ExportReadGroupSetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      projectId_ = "";

      exportUri_ = "";

      readGroupSetId_ = "";

      referenceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.genomics.v1.ReadsProto.internal_static_google_genomics_v1_ExportReadGroupSetRequest_descriptor;
    }

    public com.google.genomics.v1.ExportReadGroupSetRequest getDefaultInstanceForType() {
      return com.google.genomics.v1.ExportReadGroupSetRequest.getDefaultInstance();
    }

    public com.google.genomics.v1.ExportReadGroupSetRequest build() {
      com.google.genomics.v1.ExportReadGroupSetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.genomics.v1.ExportReadGroupSetRequest buildPartial() {
      com.google.genomics.v1.ExportReadGroupSetRequest result = new com.google.genomics.v1.ExportReadGroupSetRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.projectId_ = projectId_;
      result.exportUri_ = exportUri_;
      result.readGroupSetId_ = readGroupSetId_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        referenceNames_ = referenceNames_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.referenceNames_ = referenceNames_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.genomics.v1.ExportReadGroupSetRequest) {
        return mergeFrom((com.google.genomics.v1.ExportReadGroupSetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.genomics.v1.ExportReadGroupSetRequest other) {
      if (other == com.google.genomics.v1.ExportReadGroupSetRequest.getDefaultInstance()) return this;
      if (!other.getProjectId().isEmpty()) {
        projectId_ = other.projectId_;
        onChanged();
      }
      if (!other.getExportUri().isEmpty()) {
        exportUri_ = other.exportUri_;
        onChanged();
      }
      if (!other.getReadGroupSetId().isEmpty()) {
        readGroupSetId_ = other.readGroupSetId_;
        onChanged();
      }
      if (!other.referenceNames_.isEmpty()) {
        if (referenceNames_.isEmpty()) {
          referenceNames_ = other.referenceNames_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureReferenceNamesIsMutable();
          referenceNames_.addAll(other.referenceNames_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.genomics.v1.ExportReadGroupSetRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.genomics.v1.ExportReadGroupSetRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object projectId_ = "";
    /**
     * <pre>
     * Required. The Google Cloud project ID that owns this
     * export. The caller must have WRITE access to this project.
     * </pre>
     *
     * <code>string project_id = 1;</code>
     */
    public java.lang.String getProjectId() {
      java.lang.Object ref = projectId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. The Google Cloud project ID that owns this
     * export. The caller must have WRITE access to this project.
     * </pre>
     *
     * <code>string project_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProjectIdBytes() {
      java.lang.Object ref = projectId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. The Google Cloud project ID that owns this
     * export. The caller must have WRITE access to this project.
     * </pre>
     *
     * <code>string project_id = 1;</code>
     */
    public Builder setProjectId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      projectId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The Google Cloud project ID that owns this
     * export. The caller must have WRITE access to this project.
     * </pre>
     *
     * <code>string project_id = 1;</code>
     */
    public Builder clearProjectId() {
      
      projectId_ = getDefaultInstance().getProjectId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The Google Cloud project ID that owns this
     * export. The caller must have WRITE access to this project.
     * </pre>
     *
     * <code>string project_id = 1;</code>
     */
    public Builder setProjectIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      projectId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object exportUri_ = "";
    /**
     * <pre>
     * Required. A Google Cloud Storage URI for the exported BAM file.
     * The currently authenticated user must have write access to the new file.
     * An error will be returned if the URI already contains data.
     * </pre>
     *
     * <code>string export_uri = 2;</code>
     */
    public java.lang.String getExportUri() {
      java.lang.Object ref = exportUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exportUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. A Google Cloud Storage URI for the exported BAM file.
     * The currently authenticated user must have write access to the new file.
     * An error will be returned if the URI already contains data.
     * </pre>
     *
     * <code>string export_uri = 2;</code>
     */
    public com.google.protobuf.ByteString
        getExportUriBytes() {
      java.lang.Object ref = exportUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exportUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. A Google Cloud Storage URI for the exported BAM file.
     * The currently authenticated user must have write access to the new file.
     * An error will be returned if the URI already contains data.
     * </pre>
     *
     * <code>string export_uri = 2;</code>
     */
    public Builder setExportUri(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      exportUri_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. A Google Cloud Storage URI for the exported BAM file.
     * The currently authenticated user must have write access to the new file.
     * An error will be returned if the URI already contains data.
     * </pre>
     *
     * <code>string export_uri = 2;</code>
     */
    public Builder clearExportUri() {
      
      exportUri_ = getDefaultInstance().getExportUri();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. A Google Cloud Storage URI for the exported BAM file.
     * The currently authenticated user must have write access to the new file.
     * An error will be returned if the URI already contains data.
     * </pre>
     *
     * <code>string export_uri = 2;</code>
     */
    public Builder setExportUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      exportUri_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object readGroupSetId_ = "";
    /**
     * <pre>
     * Required. The ID of the read group set to export. The caller must have
     * READ access to this read group set.
     * </pre>
     *
     * <code>string read_group_set_id = 3;</code>
     */
    public java.lang.String getReadGroupSetId() {
      java.lang.Object ref = readGroupSetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readGroupSetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. The ID of the read group set to export. The caller must have
     * READ access to this read group set.
     * </pre>
     *
     * <code>string read_group_set_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReadGroupSetIdBytes() {
      java.lang.Object ref = readGroupSetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readGroupSetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. The ID of the read group set to export. The caller must have
     * READ access to this read group set.
     * </pre>
     *
     * <code>string read_group_set_id = 3;</code>
     */
    public Builder setReadGroupSetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      readGroupSetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The ID of the read group set to export. The caller must have
     * READ access to this read group set.
     * </pre>
     *
     * <code>string read_group_set_id = 3;</code>
     */
    public Builder clearReadGroupSetId() {
      
      readGroupSetId_ = getDefaultInstance().getReadGroupSetId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The ID of the read group set to export. The caller must have
     * READ access to this read group set.
     * </pre>
     *
     * <code>string read_group_set_id = 3;</code>
     */
    public Builder setReadGroupSetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      readGroupSetId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList referenceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureReferenceNamesIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        referenceNames_ = new com.google.protobuf.LazyStringArrayList(referenceNames_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <pre>
     * The reference names to export. If this is not specified, all reference
     * sequences, including unmapped reads, are exported.
     * Use `*` to export only unmapped reads.
     * </pre>
     *
     * <code>repeated string reference_names = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getReferenceNamesList() {
      return referenceNames_.getUnmodifiableView();
    }
    /**
     * <pre>
     * The reference names to export. If this is not specified, all reference
     * sequences, including unmapped reads, are exported.
     * Use `*` to export only unmapped reads.
     * </pre>
     *
     * <code>repeated string reference_names = 4;</code>
     */
    public int getReferenceNamesCount() {
      return referenceNames_.size();
    }
    /**
     * <pre>
     * The reference names to export. If this is not specified, all reference
     * sequences, including unmapped reads, are exported.
     * Use `*` to export only unmapped reads.
     * </pre>
     *
     * <code>repeated string reference_names = 4;</code>
     */
    public java.lang.String getReferenceNames(int index) {
      return referenceNames_.get(index);
    }
    /**
     * <pre>
     * The reference names to export. If this is not specified, all reference
     * sequences, including unmapped reads, are exported.
     * Use `*` to export only unmapped reads.
     * </pre>
     *
     * <code>repeated string reference_names = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReferenceNamesBytes(int index) {
      return referenceNames_.getByteString(index);
    }
    /**
     * <pre>
     * The reference names to export. If this is not specified, all reference
     * sequences, including unmapped reads, are exported.
     * Use `*` to export only unmapped reads.
     * </pre>
     *
     * <code>repeated string reference_names = 4;</code>
     */
    public Builder setReferenceNames(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReferenceNamesIsMutable();
      referenceNames_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The reference names to export. If this is not specified, all reference
     * sequences, including unmapped reads, are exported.
     * Use `*` to export only unmapped reads.
     * </pre>
     *
     * <code>repeated string reference_names = 4;</code>
     */
    public Builder addReferenceNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReferenceNamesIsMutable();
      referenceNames_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The reference names to export. If this is not specified, all reference
     * sequences, including unmapped reads, are exported.
     * Use `*` to export only unmapped reads.
     * </pre>
     *
     * <code>repeated string reference_names = 4;</code>
     */
    public Builder addAllReferenceNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureReferenceNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, referenceNames_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The reference names to export. If this is not specified, all reference
     * sequences, including unmapped reads, are exported.
     * Use `*` to export only unmapped reads.
     * </pre>
     *
     * <code>repeated string reference_names = 4;</code>
     */
    public Builder clearReferenceNames() {
      referenceNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The reference names to export. If this is not specified, all reference
     * sequences, including unmapped reads, are exported.
     * Use `*` to export only unmapped reads.
     * </pre>
     *
     * <code>repeated string reference_names = 4;</code>
     */
    public Builder addReferenceNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureReferenceNamesIsMutable();
      referenceNames_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.genomics.v1.ExportReadGroupSetRequest)
  }

  // @@protoc_insertion_point(class_scope:google.genomics.v1.ExportReadGroupSetRequest)
  private static final com.google.genomics.v1.ExportReadGroupSetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.genomics.v1.ExportReadGroupSetRequest();
  }

  public static com.google.genomics.v1.ExportReadGroupSetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExportReadGroupSetRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExportReadGroupSetRequest>() {
    public ExportReadGroupSetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExportReadGroupSetRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExportReadGroupSetRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExportReadGroupSetRequest> getParserForType() {
    return PARSER;
  }

  public com.google.genomics.v1.ExportReadGroupSetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

