// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/references.proto

package com.google.genomics.v1;

public interface ListBasesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.genomics.v1.ListBasesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The ID of the reference.
   * </pre>
   *
   * <code>string reference_id = 1;</code>
   */
  java.lang.String getReferenceId();
  /**
   * <pre>
   * The ID of the reference.
   * </pre>
   *
   * <code>string reference_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getReferenceIdBytes();

  /**
   * <pre>
   * The start position (0-based) of this query. Defaults to 0.
   * </pre>
   *
   * <code>int64 start = 2;</code>
   */
  long getStart();

  /**
   * <pre>
   * The end position (0-based, exclusive) of this query. Defaults to the length
   * of this reference.
   * </pre>
   *
   * <code>int64 end = 3;</code>
   */
  long getEnd();

  /**
   * <pre>
   * The continuation token, which is used to page through large result sets.
   * To get the next page of results, set this parameter to the value of
   * `nextPageToken` from the previous response.
   * </pre>
   *
   * <code>string page_token = 4;</code>
   */
  java.lang.String getPageToken();
  /**
   * <pre>
   * The continuation token, which is used to page through large result sets.
   * To get the next page of results, set this parameter to the value of
   * `nextPageToken` from the previous response.
   * </pre>
   *
   * <code>string page_token = 4;</code>
   */
  com.google.protobuf.ByteString
      getPageTokenBytes();

  /**
   * <pre>
   * The maximum number of bases to return in a single page. If unspecified,
   * defaults to 200Kbp (kilo base pairs). The maximum value is 10Mbp (mega base
   * pairs).
   * </pre>
   *
   * <code>int32 page_size = 5;</code>
   */
  int getPageSize();
}
