// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/cloudbuild/v1/cloudbuild.proto

package com.google.cloudbuild.v1;

public final class Cloudbuild {
  private Cloudbuild() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_StorageSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_StorageSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_RepoSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_RepoSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_Source_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Source_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_BuiltImage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuiltImage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_BuildStep_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuildStep_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_Results_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Results_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_Build_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Build_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_Build_SubstitutionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Build_SubstitutionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_BuildOperationMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuildOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_SourceProvenance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_SourceProvenance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_SourceProvenance_FileHashesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_SourceProvenance_FileHashesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_FileHashes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_FileHashes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_Hash_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Hash_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_CreateBuildRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_CreateBuildRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_GetBuildRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_GetBuildRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_ListBuildsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_ListBuildsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_ListBuildsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_ListBuildsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_CancelBuildRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_CancelBuildRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_BuildTrigger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuildTrigger_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_BuildTrigger_SubstitutionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuildTrigger_SubstitutionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_CreateBuildTriggerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_CreateBuildTriggerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_GetBuildTriggerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_GetBuildTriggerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_DeleteBuildTriggerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_DeleteBuildTriggerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_UpdateBuildTriggerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_UpdateBuildTriggerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_cloudbuild_v1_BuildOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuildOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.google/devtools/cloudbuild/v1/cloudbui" +
      "ld.proto\022\035google.devtools.cloudbuild.v1\032" +
      "\034google/api/annotations.proto\032#google/lo" +
      "ngrunning/operations.proto\032\036google/proto" +
      "buf/duration.proto\032\033google/protobuf/empt" +
      "y.proto\032\037google/protobuf/timestamp.proto" +
      "\"C\n\rStorageSource\022\016\n\006bucket\030\001 \001(\t\022\016\n\006obj" +
      "ect\030\002 \001(\t\022\022\n\ngeneration\030\003 \001(\003\"\200\001\n\nRepoSo" +
      "urce\022\022\n\nproject_id\030\001 \001(\t\022\021\n\trepo_name\030\002 " +
      "\001(\t\022\025\n\013branch_name\030\003 \001(\tH\000\022\022\n\010tag_name\030\004",
      " \001(\tH\000\022\024\n\ncommit_sha\030\005 \001(\tH\000B\n\n\010revision" +
      "\"\234\001\n\006Source\022F\n\016storage_source\030\002 \001(\0132,.go" +
      "ogle.devtools.cloudbuild.v1.StorageSourc" +
      "eH\000\022@\n\013repo_source\030\003 \001(\0132).google.devtoo" +
      "ls.cloudbuild.v1.RepoSourceH\000B\010\n\006source\"" +
      "*\n\nBuiltImage\022\014\n\004name\030\001 \001(\t\022\016\n\006digest\030\003 " +
      "\001(\t\"s\n\tBuildStep\022\014\n\004name\030\001 \001(\t\022\013\n\003env\030\002 " +
      "\003(\t\022\014\n\004args\030\003 \003(\t\022\013\n\003dir\030\004 \001(\t\022\n\n\002id\030\005 \001" +
      "(\t\022\020\n\010wait_for\030\006 \003(\t\022\022\n\nentrypoint\030\007 \001(\t" +
      "\"_\n\007Results\0229\n\006images\030\002 \003(\0132).google.dev",
      "tools.cloudbuild.v1.BuiltImage\022\031\n\021build_" +
      "step_images\030\003 \003(\t\"\303\007\n\005Build\022\n\n\002id\030\001 \001(\t\022" +
      "\022\n\nproject_id\030\020 \001(\t\022;\n\006status\030\002 \001(\0162+.go" +
      "ogle.devtools.cloudbuild.v1.Build.Status" +
      "\022\025\n\rstatus_detail\030\030 \001(\t\0225\n\006source\030\003 \001(\0132" +
      "%.google.devtools.cloudbuild.v1.Source\0227" +
      "\n\005steps\030\013 \003(\0132(.google.devtools.cloudbui" +
      "ld.v1.BuildStep\0227\n\007results\030\n \001(\0132&.googl" +
      "e.devtools.cloudbuild.v1.Results\022/\n\013crea" +
      "te_time\030\006 \001(\0132\032.google.protobuf.Timestam",
      "p\022.\n\nstart_time\030\007 \001(\0132\032.google.protobuf." +
      "Timestamp\022/\n\013finish_time\030\010 \001(\0132\032.google." +
      "protobuf.Timestamp\022*\n\007timeout\030\014 \001(\0132\031.go" +
      "ogle.protobuf.Duration\022\016\n\006images\030\r \003(\t\022\023" +
      "\n\013logs_bucket\030\023 \001(\t\022J\n\021source_provenance" +
      "\030\025 \001(\0132/.google.devtools.cloudbuild.v1.S" +
      "ourceProvenance\022\030\n\020build_trigger_id\030\026 \001(" +
      "\t\022<\n\007options\030\027 \001(\0132+.google.devtools.clo" +
      "udbuild.v1.BuildOptions\022\017\n\007log_url\030\031 \001(\t" +
      "\022N\n\rsubstitutions\030\035 \003(\01327.google.devtool",
      "s.cloudbuild.v1.Build.SubstitutionsEntry" +
      "\0324\n\022SubstitutionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\t:\0028\001\"\177\n\006Status\022\022\n\016STATUS_UNKNO" +
      "WN\020\000\022\n\n\006QUEUED\020\001\022\013\n\007WORKING\020\002\022\013\n\007SUCCESS" +
      "\020\003\022\013\n\007FAILURE\020\004\022\022\n\016INTERNAL_ERROR\020\005\022\013\n\007T" +
      "IMEOUT\020\006\022\r\n\tCANCELLED\020\007\"M\n\026BuildOperatio" +
      "nMetadata\0223\n\005build\030\001 \001(\0132$.google.devtoo" +
      "ls.cloudbuild.v1.Build\"\336\002\n\020SourceProvena" +
      "nce\022M\n\027resolved_storage_source\030\003 \001(\0132,.g" +
      "oogle.devtools.cloudbuild.v1.StorageSour",
      "ce\022G\n\024resolved_repo_source\030\006 \001(\0132).googl" +
      "e.devtools.cloudbuild.v1.RepoSource\022T\n\013f" +
      "ile_hashes\030\004 \003(\0132?.google.devtools.cloud" +
      "build.v1.SourceProvenance.FileHashesEntr" +
      "y\032\\\n\017FileHashesEntry\022\013\n\003key\030\001 \001(\t\0228\n\005val" +
      "ue\030\002 \001(\0132).google.devtools.cloudbuild.v1" +
      ".FileHashes:\0028\001\"D\n\nFileHashes\0226\n\tfile_ha" +
      "sh\030\001 \003(\0132#.google.devtools.cloudbuild.v1" +
      ".Hash\"s\n\004Hash\022:\n\004type\030\001 \001(\0162,.google.dev" +
      "tools.cloudbuild.v1.Hash.HashType\022\r\n\005val",
      "ue\030\002 \001(\014\" \n\010HashType\022\010\n\004NONE\020\000\022\n\n\006SHA256" +
      "\020\001\"]\n\022CreateBuildRequest\022\022\n\nproject_id\030\001" +
      " \001(\t\0223\n\005build\030\002 \001(\0132$.google.devtools.cl" +
      "oudbuild.v1.Build\"1\n\017GetBuildRequest\022\022\n\n" +
      "project_id\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\"^\n\021ListBuil" +
      "dsRequest\022\022\n\nproject_id\030\001 \001(\t\022\021\n\tpage_si" +
      "ze\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t\022\016\n\006filter\030\010" +
      " \001(\t\"c\n\022ListBuildsResponse\0224\n\006builds\030\001 \003" +
      "(\0132$.google.devtools.cloudbuild.v1.Build" +
      "\022\027\n\017next_page_token\030\002 \001(\t\"4\n\022CancelBuild",
      "Request\022\022\n\nproject_id\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\"" +
      "\241\003\n\014BuildTrigger\022\n\n\002id\030\001 \001(\t\022\023\n\013descript" +
      "ion\030\n \001(\t\022C\n\020trigger_template\030\007 \001(\0132).go" +
      "ogle.devtools.cloudbuild.v1.RepoSource\0225" +
      "\n\005build\030\004 \001(\0132$.google.devtools.cloudbui" +
      "ld.v1.BuildH\000\022\022\n\010filename\030\010 \001(\tH\000\022/\n\013cre" +
      "ate_time\030\005 \001(\0132\032.google.protobuf.Timesta" +
      "mp\022\020\n\010disabled\030\t \001(\010\022U\n\rsubstitutions\030\013 " +
      "\003(\0132>.google.devtools.cloudbuild.v1.Buil" +
      "dTrigger.SubstitutionsEntry\0324\n\022Substitut",
      "ionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001B\020\n\016build_template\"m\n\031CreateBuildTrigge" +
      "rRequest\022\022\n\nproject_id\030\001 \001(\t\022<\n\007trigger\030" +
      "\002 \001(\0132+.google.devtools.cloudbuild.v1.Bu" +
      "ildTrigger\"@\n\026GetBuildTriggerRequest\022\022\n\n" +
      "project_id\030\001 \001(\t\022\022\n\ntrigger_id\030\002 \001(\t\".\n\030" +
      "ListBuildTriggersRequest\022\022\n\nproject_id\030\001" +
      " \001(\t\"Z\n\031ListBuildTriggersResponse\022=\n\010tri" +
      "ggers\030\001 \003(\0132+.google.devtools.cloudbuild" +
      ".v1.BuildTrigger\"C\n\031DeleteBuildTriggerRe",
      "quest\022\022\n\nproject_id\030\001 \001(\t\022\022\n\ntrigger_id\030" +
      "\002 \001(\t\"\201\001\n\031UpdateBuildTriggerRequest\022\022\n\np" +
      "roject_id\030\001 \001(\t\022\022\n\ntrigger_id\030\002 \001(\t\022<\n\007t" +
      "rigger\030\003 \001(\0132+.google.devtools.cloudbuil" +
      "d.v1.BuildTrigger\"\347\001\n\014BuildOptions\022L\n\026so" +
      "urce_provenance_hash\030\001 \003(\0162,.google.devt" +
      "ools.cloudbuild.v1.Hash.HashType\022Y\n\027requ" +
      "ested_verify_option\030\002 \001(\01628.google.devto" +
      "ols.cloudbuild.v1.BuildOptions.VerifyOpt" +
      "ion\".\n\014VerifyOption\022\020\n\014NOT_VERIFIED\020\000\022\014\n",
      "\010VERIFIED\020\0012\354\013\n\nCloudBuild\022\220\001\n\013CreateBui" +
      "ld\0221.google.devtools.cloudbuild.v1.Creat" +
      "eBuildRequest\032\035.google.longrunning.Opera" +
      "tion\"/\202\323\344\223\002)\" /v1/projects/{project_id}/" +
      "builds:\005build\022\217\001\n\010GetBuild\022..google.devt" +
      "ools.cloudbuild.v1.GetBuildRequest\032$.goo" +
      "gle.devtools.cloudbuild.v1.Build\"-\202\323\344\223\002\'" +
      "\022%/v1/projects/{project_id}/builds/{id}\022" +
      "\233\001\n\nListBuilds\0220.google.devtools.cloudbu" +
      "ild.v1.ListBuildsRequest\0321.google.devtoo",
      "ls.cloudbuild.v1.ListBuildsResponse\"(\202\323\344" +
      "\223\002\"\022 /v1/projects/{project_id}/builds\022\237\001" +
      "\n\013CancelBuild\0221.google.devtools.cloudbui" +
      "ld.v1.CancelBuildRequest\032$.google.devtoo" +
      "ls.cloudbuild.v1.Build\"7\202\323\344\223\0021\",/v1/proj" +
      "ects/{project_id}/builds/{id}:cancel:\001*\022" +
      "\260\001\n\022CreateBuildTrigger\0228.google.devtools" +
      ".cloudbuild.v1.CreateBuildTriggerRequest" +
      "\032+.google.devtools.cloudbuild.v1.BuildTr" +
      "igger\"3\202\323\344\223\002-\"\"/v1/projects/{project_id}",
      "/triggers:\007trigger\022\256\001\n\017GetBuildTrigger\0225" +
      ".google.devtools.cloudbuild.v1.GetBuildT" +
      "riggerRequest\032+.google.devtools.cloudbui" +
      "ld.v1.BuildTrigger\"7\202\323\344\223\0021\022//v1/projects" +
      "/{project_id}/triggers/{trigger_id}\022\262\001\n\021" +
      "ListBuildTriggers\0227.google.devtools.clou" +
      "dbuild.v1.ListBuildTriggersRequest\0328.goo" +
      "gle.devtools.cloudbuild.v1.ListBuildTrig" +
      "gersResponse\"*\202\323\344\223\002$\022\"/v1/projects/{proj" +
      "ect_id}/triggers\022\237\001\n\022DeleteBuildTrigger\022",
      "8.google.devtools.cloudbuild.v1.DeleteBu" +
      "ildTriggerRequest\032\026.google.protobuf.Empt" +
      "y\"7\202\323\344\223\0021*//v1/projects/{project_id}/tri" +
      "ggers/{trigger_id}\022\275\001\n\022UpdateBuildTrigge" +
      "r\0228.google.devtools.cloudbuild.v1.Update" +
      "BuildTriggerRequest\032+.google.devtools.cl" +
      "oudbuild.v1.BuildTrigger\"@\202\323\344\223\002:2//v1/pr" +
      "ojects/{project_id}/triggers/{trigger_id" +
      "}:\007triggerBk\n\030com.google.cloudbuild.v1P\001" +
      "ZGgoogle.golang.org/genproto/googleapis/",
      "devtools/cloudbuild/v1;cloudbuild\242\002\003GCBb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.longrunning.OperationsProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_google_devtools_cloudbuild_v1_StorageSource_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_devtools_cloudbuild_v1_StorageSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_StorageSource_descriptor,
        new java.lang.String[] { "Bucket", "Object", "Generation", });
    internal_static_google_devtools_cloudbuild_v1_RepoSource_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_devtools_cloudbuild_v1_RepoSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_RepoSource_descriptor,
        new java.lang.String[] { "ProjectId", "RepoName", "BranchName", "TagName", "CommitSha", "Revision", });
    internal_static_google_devtools_cloudbuild_v1_Source_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_devtools_cloudbuild_v1_Source_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_Source_descriptor,
        new java.lang.String[] { "StorageSource", "RepoSource", "Source", });
    internal_static_google_devtools_cloudbuild_v1_BuiltImage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_devtools_cloudbuild_v1_BuiltImage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_BuiltImage_descriptor,
        new java.lang.String[] { "Name", "Digest", });
    internal_static_google_devtools_cloudbuild_v1_BuildStep_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_devtools_cloudbuild_v1_BuildStep_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_BuildStep_descriptor,
        new java.lang.String[] { "Name", "Env", "Args", "Dir", "Id", "WaitFor", "Entrypoint", });
    internal_static_google_devtools_cloudbuild_v1_Results_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_devtools_cloudbuild_v1_Results_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_Results_descriptor,
        new java.lang.String[] { "Images", "BuildStepImages", });
    internal_static_google_devtools_cloudbuild_v1_Build_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_devtools_cloudbuild_v1_Build_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_Build_descriptor,
        new java.lang.String[] { "Id", "ProjectId", "Status", "StatusDetail", "Source", "Steps", "Results", "CreateTime", "StartTime", "FinishTime", "Timeout", "Images", "LogsBucket", "SourceProvenance", "BuildTriggerId", "Options", "LogUrl", "Substitutions", });
    internal_static_google_devtools_cloudbuild_v1_Build_SubstitutionsEntry_descriptor =
      internal_static_google_devtools_cloudbuild_v1_Build_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_cloudbuild_v1_Build_SubstitutionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_Build_SubstitutionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_devtools_cloudbuild_v1_BuildOperationMetadata_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_devtools_cloudbuild_v1_BuildOperationMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_BuildOperationMetadata_descriptor,
        new java.lang.String[] { "Build", });
    internal_static_google_devtools_cloudbuild_v1_SourceProvenance_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_devtools_cloudbuild_v1_SourceProvenance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_SourceProvenance_descriptor,
        new java.lang.String[] { "ResolvedStorageSource", "ResolvedRepoSource", "FileHashes", });
    internal_static_google_devtools_cloudbuild_v1_SourceProvenance_FileHashesEntry_descriptor =
      internal_static_google_devtools_cloudbuild_v1_SourceProvenance_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_cloudbuild_v1_SourceProvenance_FileHashesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_SourceProvenance_FileHashesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_devtools_cloudbuild_v1_FileHashes_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_devtools_cloudbuild_v1_FileHashes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_FileHashes_descriptor,
        new java.lang.String[] { "FileHash", });
    internal_static_google_devtools_cloudbuild_v1_Hash_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_devtools_cloudbuild_v1_Hash_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_Hash_descriptor,
        new java.lang.String[] { "Type", "Value", });
    internal_static_google_devtools_cloudbuild_v1_CreateBuildRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_devtools_cloudbuild_v1_CreateBuildRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_CreateBuildRequest_descriptor,
        new java.lang.String[] { "ProjectId", "Build", });
    internal_static_google_devtools_cloudbuild_v1_GetBuildRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_devtools_cloudbuild_v1_GetBuildRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_GetBuildRequest_descriptor,
        new java.lang.String[] { "ProjectId", "Id", });
    internal_static_google_devtools_cloudbuild_v1_ListBuildsRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_devtools_cloudbuild_v1_ListBuildsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_ListBuildsRequest_descriptor,
        new java.lang.String[] { "ProjectId", "PageSize", "PageToken", "Filter", });
    internal_static_google_devtools_cloudbuild_v1_ListBuildsResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_devtools_cloudbuild_v1_ListBuildsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_ListBuildsResponse_descriptor,
        new java.lang.String[] { "Builds", "NextPageToken", });
    internal_static_google_devtools_cloudbuild_v1_CancelBuildRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_devtools_cloudbuild_v1_CancelBuildRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_CancelBuildRequest_descriptor,
        new java.lang.String[] { "ProjectId", "Id", });
    internal_static_google_devtools_cloudbuild_v1_BuildTrigger_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_devtools_cloudbuild_v1_BuildTrigger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_BuildTrigger_descriptor,
        new java.lang.String[] { "Id", "Description", "TriggerTemplate", "Build", "Filename", "CreateTime", "Disabled", "Substitutions", "BuildTemplate", });
    internal_static_google_devtools_cloudbuild_v1_BuildTrigger_SubstitutionsEntry_descriptor =
      internal_static_google_devtools_cloudbuild_v1_BuildTrigger_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_cloudbuild_v1_BuildTrigger_SubstitutionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_BuildTrigger_SubstitutionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_devtools_cloudbuild_v1_CreateBuildTriggerRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_devtools_cloudbuild_v1_CreateBuildTriggerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_CreateBuildTriggerRequest_descriptor,
        new java.lang.String[] { "ProjectId", "Trigger", });
    internal_static_google_devtools_cloudbuild_v1_GetBuildTriggerRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_devtools_cloudbuild_v1_GetBuildTriggerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_GetBuildTriggerRequest_descriptor,
        new java.lang.String[] { "ProjectId", "TriggerId", });
    internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersRequest_descriptor,
        new java.lang.String[] { "ProjectId", });
    internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersResponse_descriptor,
        new java.lang.String[] { "Triggers", });
    internal_static_google_devtools_cloudbuild_v1_DeleteBuildTriggerRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_google_devtools_cloudbuild_v1_DeleteBuildTriggerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_DeleteBuildTriggerRequest_descriptor,
        new java.lang.String[] { "ProjectId", "TriggerId", });
    internal_static_google_devtools_cloudbuild_v1_UpdateBuildTriggerRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_google_devtools_cloudbuild_v1_UpdateBuildTriggerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_UpdateBuildTriggerRequest_descriptor,
        new java.lang.String[] { "ProjectId", "TriggerId", "Trigger", });
    internal_static_google_devtools_cloudbuild_v1_BuildOptions_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_google_devtools_cloudbuild_v1_BuildOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_cloudbuild_v1_BuildOptions_descriptor,
        new java.lang.String[] { "SourceProvenanceHash", "RequestedVerifyOption", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
