// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1alpha2/pipelines.proto

package com.google.genomics.v1a;

/**
 * <pre>
 * Request to set operation status. Should only be used by VMs
 * created by the Pipelines Service and not by end users.
 * </pre>
 *
 * Protobuf type {@code google.genomics.v1alpha2.SetOperationStatusRequest}
 */
public  final class SetOperationStatusRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.genomics.v1alpha2.SetOperationStatusRequest)
    SetOperationStatusRequestOrBuilder {
  // Use SetOperationStatusRequest.newBuilder() to construct.
  private SetOperationStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetOperationStatusRequest() {
    operationId_ = "";
    timestampEvents_ = java.util.Collections.emptyList();
    errorCode_ = 0;
    errorMessage_ = "";
    validationToken_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SetOperationStatusRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            operationId_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              timestampEvents_ = new java.util.ArrayList<com.google.genomics.v1a.TimestampEvent>();
              mutable_bitField0_ |= 0x00000002;
            }
            timestampEvents_.add(
                input.readMessage(com.google.genomics.v1a.TimestampEvent.parser(), extensionRegistry));
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            errorCode_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            errorMessage_ = s;
            break;
          }
          case 40: {

            validationToken_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        timestampEvents_ = java.util.Collections.unmodifiableList(timestampEvents_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.genomics.v1a.PipelinesProto.internal_static_google_genomics_v1alpha2_SetOperationStatusRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.genomics.v1a.PipelinesProto.internal_static_google_genomics_v1alpha2_SetOperationStatusRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.genomics.v1a.SetOperationStatusRequest.class, com.google.genomics.v1a.SetOperationStatusRequest.Builder.class);
  }

  private int bitField0_;
  public static final int OPERATION_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object operationId_;
  /**
   * <code>string operation_id = 1;</code>
   */
  public java.lang.String getOperationId() {
    java.lang.Object ref = operationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operationId_ = s;
      return s;
    }
  }
  /**
   * <code>string operation_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOperationIdBytes() {
    java.lang.Object ref = operationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_EVENTS_FIELD_NUMBER = 2;
  private java.util.List<com.google.genomics.v1a.TimestampEvent> timestampEvents_;
  /**
   * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
   */
  public java.util.List<com.google.genomics.v1a.TimestampEvent> getTimestampEventsList() {
    return timestampEvents_;
  }
  /**
   * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
   */
  public java.util.List<? extends com.google.genomics.v1a.TimestampEventOrBuilder> 
      getTimestampEventsOrBuilderList() {
    return timestampEvents_;
  }
  /**
   * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
   */
  public int getTimestampEventsCount() {
    return timestampEvents_.size();
  }
  /**
   * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
   */
  public com.google.genomics.v1a.TimestampEvent getTimestampEvents(int index) {
    return timestampEvents_.get(index);
  }
  /**
   * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
   */
  public com.google.genomics.v1a.TimestampEventOrBuilder getTimestampEventsOrBuilder(
      int index) {
    return timestampEvents_.get(index);
  }

  public static final int ERROR_CODE_FIELD_NUMBER = 3;
  private int errorCode_;
  /**
   * <code>.google.rpc.Code error_code = 3;</code>
   */
  public int getErrorCodeValue() {
    return errorCode_;
  }
  /**
   * <code>.google.rpc.Code error_code = 3;</code>
   */
  public com.google.rpc.Code getErrorCode() {
    com.google.rpc.Code result = com.google.rpc.Code.valueOf(errorCode_);
    return result == null ? com.google.rpc.Code.UNRECOGNIZED : result;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 4;
  private volatile java.lang.Object errorMessage_;
  /**
   * <code>string error_message = 4;</code>
   */
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string error_message = 4;</code>
   */
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALIDATION_TOKEN_FIELD_NUMBER = 5;
  private long validationToken_;
  /**
   * <code>uint64 validation_token = 5;</code>
   */
  public long getValidationToken() {
    return validationToken_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOperationIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operationId_);
    }
    for (int i = 0; i < timestampEvents_.size(); i++) {
      output.writeMessage(2, timestampEvents_.get(i));
    }
    if (errorCode_ != com.google.rpc.Code.OK.getNumber()) {
      output.writeEnum(3, errorCode_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errorMessage_);
    }
    if (validationToken_ != 0L) {
      output.writeUInt64(5, validationToken_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOperationIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operationId_);
    }
    for (int i = 0; i < timestampEvents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, timestampEvents_.get(i));
    }
    if (errorCode_ != com.google.rpc.Code.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, errorCode_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, errorMessage_);
    }
    if (validationToken_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, validationToken_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.genomics.v1a.SetOperationStatusRequest)) {
      return super.equals(obj);
    }
    com.google.genomics.v1a.SetOperationStatusRequest other = (com.google.genomics.v1a.SetOperationStatusRequest) obj;

    boolean result = true;
    result = result && getOperationId()
        .equals(other.getOperationId());
    result = result && getTimestampEventsList()
        .equals(other.getTimestampEventsList());
    result = result && errorCode_ == other.errorCode_;
    result = result && getErrorMessage()
        .equals(other.getErrorMessage());
    result = result && (getValidationToken()
        == other.getValidationToken());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPERATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOperationId().hashCode();
    if (getTimestampEventsCount() > 0) {
      hash = (37 * hash) + TIMESTAMP_EVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getTimestampEventsList().hashCode();
    }
    hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
    hash = (53 * hash) + errorCode_;
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (37 * hash) + VALIDATION_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValidationToken());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.genomics.v1a.SetOperationStatusRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1a.SetOperationStatusRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1a.SetOperationStatusRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1a.SetOperationStatusRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1a.SetOperationStatusRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.genomics.v1a.SetOperationStatusRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.genomics.v1a.SetOperationStatusRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.genomics.v1a.SetOperationStatusRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.genomics.v1a.SetOperationStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.genomics.v1a.SetOperationStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.genomics.v1a.SetOperationStatusRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request to set operation status. Should only be used by VMs
   * created by the Pipelines Service and not by end users.
   * </pre>
   *
   * Protobuf type {@code google.genomics.v1alpha2.SetOperationStatusRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.genomics.v1alpha2.SetOperationStatusRequest)
      com.google.genomics.v1a.SetOperationStatusRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.genomics.v1a.PipelinesProto.internal_static_google_genomics_v1alpha2_SetOperationStatusRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.genomics.v1a.PipelinesProto.internal_static_google_genomics_v1alpha2_SetOperationStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.genomics.v1a.SetOperationStatusRequest.class, com.google.genomics.v1a.SetOperationStatusRequest.Builder.class);
    }

    // Construct using com.google.genomics.v1a.SetOperationStatusRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTimestampEventsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      operationId_ = "";

      if (timestampEventsBuilder_ == null) {
        timestampEvents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        timestampEventsBuilder_.clear();
      }
      errorCode_ = 0;

      errorMessage_ = "";

      validationToken_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.genomics.v1a.PipelinesProto.internal_static_google_genomics_v1alpha2_SetOperationStatusRequest_descriptor;
    }

    public com.google.genomics.v1a.SetOperationStatusRequest getDefaultInstanceForType() {
      return com.google.genomics.v1a.SetOperationStatusRequest.getDefaultInstance();
    }

    public com.google.genomics.v1a.SetOperationStatusRequest build() {
      com.google.genomics.v1a.SetOperationStatusRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.genomics.v1a.SetOperationStatusRequest buildPartial() {
      com.google.genomics.v1a.SetOperationStatusRequest result = new com.google.genomics.v1a.SetOperationStatusRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.operationId_ = operationId_;
      if (timestampEventsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          timestampEvents_ = java.util.Collections.unmodifiableList(timestampEvents_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.timestampEvents_ = timestampEvents_;
      } else {
        result.timestampEvents_ = timestampEventsBuilder_.build();
      }
      result.errorCode_ = errorCode_;
      result.errorMessage_ = errorMessage_;
      result.validationToken_ = validationToken_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.genomics.v1a.SetOperationStatusRequest) {
        return mergeFrom((com.google.genomics.v1a.SetOperationStatusRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.genomics.v1a.SetOperationStatusRequest other) {
      if (other == com.google.genomics.v1a.SetOperationStatusRequest.getDefaultInstance()) return this;
      if (!other.getOperationId().isEmpty()) {
        operationId_ = other.operationId_;
        onChanged();
      }
      if (timestampEventsBuilder_ == null) {
        if (!other.timestampEvents_.isEmpty()) {
          if (timestampEvents_.isEmpty()) {
            timestampEvents_ = other.timestampEvents_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTimestampEventsIsMutable();
            timestampEvents_.addAll(other.timestampEvents_);
          }
          onChanged();
        }
      } else {
        if (!other.timestampEvents_.isEmpty()) {
          if (timestampEventsBuilder_.isEmpty()) {
            timestampEventsBuilder_.dispose();
            timestampEventsBuilder_ = null;
            timestampEvents_ = other.timestampEvents_;
            bitField0_ = (bitField0_ & ~0x00000002);
            timestampEventsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTimestampEventsFieldBuilder() : null;
          } else {
            timestampEventsBuilder_.addAllMessages(other.timestampEvents_);
          }
        }
      }
      if (other.errorCode_ != 0) {
        setErrorCodeValue(other.getErrorCodeValue());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      if (other.getValidationToken() != 0L) {
        setValidationToken(other.getValidationToken());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.genomics.v1a.SetOperationStatusRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.genomics.v1a.SetOperationStatusRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object operationId_ = "";
    /**
     * <code>string operation_id = 1;</code>
     */
    public java.lang.String getOperationId() {
      java.lang.Object ref = operationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string operation_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOperationIdBytes() {
      java.lang.Object ref = operationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string operation_id = 1;</code>
     */
    public Builder setOperationId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      operationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string operation_id = 1;</code>
     */
    public Builder clearOperationId() {
      
      operationId_ = getDefaultInstance().getOperationId();
      onChanged();
      return this;
    }
    /**
     * <code>string operation_id = 1;</code>
     */
    public Builder setOperationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      operationId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.google.genomics.v1a.TimestampEvent> timestampEvents_ =
      java.util.Collections.emptyList();
    private void ensureTimestampEventsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        timestampEvents_ = new java.util.ArrayList<com.google.genomics.v1a.TimestampEvent>(timestampEvents_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.genomics.v1a.TimestampEvent, com.google.genomics.v1a.TimestampEvent.Builder, com.google.genomics.v1a.TimestampEventOrBuilder> timestampEventsBuilder_;

    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public java.util.List<com.google.genomics.v1a.TimestampEvent> getTimestampEventsList() {
      if (timestampEventsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(timestampEvents_);
      } else {
        return timestampEventsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public int getTimestampEventsCount() {
      if (timestampEventsBuilder_ == null) {
        return timestampEvents_.size();
      } else {
        return timestampEventsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public com.google.genomics.v1a.TimestampEvent getTimestampEvents(int index) {
      if (timestampEventsBuilder_ == null) {
        return timestampEvents_.get(index);
      } else {
        return timestampEventsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public Builder setTimestampEvents(
        int index, com.google.genomics.v1a.TimestampEvent value) {
      if (timestampEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimestampEventsIsMutable();
        timestampEvents_.set(index, value);
        onChanged();
      } else {
        timestampEventsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public Builder setTimestampEvents(
        int index, com.google.genomics.v1a.TimestampEvent.Builder builderForValue) {
      if (timestampEventsBuilder_ == null) {
        ensureTimestampEventsIsMutable();
        timestampEvents_.set(index, builderForValue.build());
        onChanged();
      } else {
        timestampEventsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public Builder addTimestampEvents(com.google.genomics.v1a.TimestampEvent value) {
      if (timestampEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimestampEventsIsMutable();
        timestampEvents_.add(value);
        onChanged();
      } else {
        timestampEventsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public Builder addTimestampEvents(
        int index, com.google.genomics.v1a.TimestampEvent value) {
      if (timestampEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimestampEventsIsMutable();
        timestampEvents_.add(index, value);
        onChanged();
      } else {
        timestampEventsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public Builder addTimestampEvents(
        com.google.genomics.v1a.TimestampEvent.Builder builderForValue) {
      if (timestampEventsBuilder_ == null) {
        ensureTimestampEventsIsMutable();
        timestampEvents_.add(builderForValue.build());
        onChanged();
      } else {
        timestampEventsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public Builder addTimestampEvents(
        int index, com.google.genomics.v1a.TimestampEvent.Builder builderForValue) {
      if (timestampEventsBuilder_ == null) {
        ensureTimestampEventsIsMutable();
        timestampEvents_.add(index, builderForValue.build());
        onChanged();
      } else {
        timestampEventsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public Builder addAllTimestampEvents(
        java.lang.Iterable<? extends com.google.genomics.v1a.TimestampEvent> values) {
      if (timestampEventsBuilder_ == null) {
        ensureTimestampEventsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, timestampEvents_);
        onChanged();
      } else {
        timestampEventsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public Builder clearTimestampEvents() {
      if (timestampEventsBuilder_ == null) {
        timestampEvents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        timestampEventsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public Builder removeTimestampEvents(int index) {
      if (timestampEventsBuilder_ == null) {
        ensureTimestampEventsIsMutable();
        timestampEvents_.remove(index);
        onChanged();
      } else {
        timestampEventsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public com.google.genomics.v1a.TimestampEvent.Builder getTimestampEventsBuilder(
        int index) {
      return getTimestampEventsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public com.google.genomics.v1a.TimestampEventOrBuilder getTimestampEventsOrBuilder(
        int index) {
      if (timestampEventsBuilder_ == null) {
        return timestampEvents_.get(index);  } else {
        return timestampEventsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public java.util.List<? extends com.google.genomics.v1a.TimestampEventOrBuilder> 
         getTimestampEventsOrBuilderList() {
      if (timestampEventsBuilder_ != null) {
        return timestampEventsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(timestampEvents_);
      }
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public com.google.genomics.v1a.TimestampEvent.Builder addTimestampEventsBuilder() {
      return getTimestampEventsFieldBuilder().addBuilder(
          com.google.genomics.v1a.TimestampEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public com.google.genomics.v1a.TimestampEvent.Builder addTimestampEventsBuilder(
        int index) {
      return getTimestampEventsFieldBuilder().addBuilder(
          index, com.google.genomics.v1a.TimestampEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .google.genomics.v1alpha2.TimestampEvent timestamp_events = 2;</code>
     */
    public java.util.List<com.google.genomics.v1a.TimestampEvent.Builder> 
         getTimestampEventsBuilderList() {
      return getTimestampEventsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.genomics.v1a.TimestampEvent, com.google.genomics.v1a.TimestampEvent.Builder, com.google.genomics.v1a.TimestampEventOrBuilder> 
        getTimestampEventsFieldBuilder() {
      if (timestampEventsBuilder_ == null) {
        timestampEventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.genomics.v1a.TimestampEvent, com.google.genomics.v1a.TimestampEvent.Builder, com.google.genomics.v1a.TimestampEventOrBuilder>(
                timestampEvents_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        timestampEvents_ = null;
      }
      return timestampEventsBuilder_;
    }

    private int errorCode_ = 0;
    /**
     * <code>.google.rpc.Code error_code = 3;</code>
     */
    public int getErrorCodeValue() {
      return errorCode_;
    }
    /**
     * <code>.google.rpc.Code error_code = 3;</code>
     */
    public Builder setErrorCodeValue(int value) {
      errorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.google.rpc.Code error_code = 3;</code>
     */
    public com.google.rpc.Code getErrorCode() {
      com.google.rpc.Code result = com.google.rpc.Code.valueOf(errorCode_);
      return result == null ? com.google.rpc.Code.UNRECOGNIZED : result;
    }
    /**
     * <code>.google.rpc.Code error_code = 3;</code>
     */
    public Builder setErrorCode(com.google.rpc.Code value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      errorCode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.rpc.Code error_code = 3;</code>
     */
    public Builder clearErrorCode() {
      
      errorCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string error_message = 4;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_message = 4;</code>
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 4;</code>
     */
    public Builder clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 4;</code>
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value;
      onChanged();
      return this;
    }

    private long validationToken_ ;
    /**
     * <code>uint64 validation_token = 5;</code>
     */
    public long getValidationToken() {
      return validationToken_;
    }
    /**
     * <code>uint64 validation_token = 5;</code>
     */
    public Builder setValidationToken(long value) {
      
      validationToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 validation_token = 5;</code>
     */
    public Builder clearValidationToken() {
      
      validationToken_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.genomics.v1alpha2.SetOperationStatusRequest)
  }

  // @@protoc_insertion_point(class_scope:google.genomics.v1alpha2.SetOperationStatusRequest)
  private static final com.google.genomics.v1a.SetOperationStatusRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.genomics.v1a.SetOperationStatusRequest();
  }

  public static com.google.genomics.v1a.SetOperationStatusRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetOperationStatusRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetOperationStatusRequest>() {
    public SetOperationStatusRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetOperationStatusRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetOperationStatusRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetOperationStatusRequest> getParserForType() {
    return PARSER;
  }

  public com.google.genomics.v1a.SetOperationStatusRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

