apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: exchangeogram
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: exchangeogram
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: exchangeogram
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/grpc-kubecon-demo2017/csharpfrontend:test5
        ports:
        - containerPort: 8080