// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/functions/v1beta2/functions.proto

package com.google.cloud.functions.v1beta2;

/**
 * <pre>
 * Describes the current stage of a deployment.
 * </pre>
 *
 * Protobuf enum {@code google.cloud.functions.v1beta2.CloudFunctionStatus}
 */
public enum CloudFunctionStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Status not specified.
   * </pre>
   *
   * <code>STATUS_UNSPECIFIED = 0;</code>
   */
  STATUS_UNSPECIFIED(0),
  /**
   * <pre>
   * Successfully deployed.
   * </pre>
   *
   * <code>READY = 1;</code>
   */
  READY(1),
  /**
   * <pre>
   * Not deployed correctly - behavior is undefined. The item should be updated
   * or deleted to move it out of this state.
   * </pre>
   *
   * <code>FAILED = 2;</code>
   */
  FAILED(2),
  /**
   * <pre>
   * Creation or update in progress.
   * </pre>
   *
   * <code>DEPLOYING = 3;</code>
   */
  DEPLOYING(3),
  /**
   * <pre>
   * Deletion in progress.
   * </pre>
   *
   * <code>DELETING = 4;</code>
   */
  DELETING(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Status not specified.
   * </pre>
   *
   * <code>STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Successfully deployed.
   * </pre>
   *
   * <code>READY = 1;</code>
   */
  public static final int READY_VALUE = 1;
  /**
   * <pre>
   * Not deployed correctly - behavior is undefined. The item should be updated
   * or deleted to move it out of this state.
   * </pre>
   *
   * <code>FAILED = 2;</code>
   */
  public static final int FAILED_VALUE = 2;
  /**
   * <pre>
   * Creation or update in progress.
   * </pre>
   *
   * <code>DEPLOYING = 3;</code>
   */
  public static final int DEPLOYING_VALUE = 3;
  /**
   * <pre>
   * Deletion in progress.
   * </pre>
   *
   * <code>DELETING = 4;</code>
   */
  public static final int DELETING_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CloudFunctionStatus valueOf(int value) {
    return forNumber(value);
  }

  public static CloudFunctionStatus forNumber(int value) {
    switch (value) {
      case 0: return STATUS_UNSPECIFIED;
      case 1: return READY;
      case 2: return FAILED;
      case 3: return DEPLOYING;
      case 4: return DELETING;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CloudFunctionStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CloudFunctionStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CloudFunctionStatus>() {
          public CloudFunctionStatus findValueByNumber(int number) {
            return CloudFunctionStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.google.cloud.functions.v1beta2.FunctionsProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final CloudFunctionStatus[] VALUES = values();

  public static CloudFunctionStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CloudFunctionStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.cloud.functions.v1beta2.CloudFunctionStatus)
}

