// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/privacy/dlp/v2beta1/dlp.proto

package com.google.privacy.dlp.v2beta1;

public interface InspectOperationMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.privacy.dlp.v2beta1.InspectOperationMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Total size in bytes that were processed.
   * </pre>
   *
   * <code>int64 processed_bytes = 1;</code>
   */
  long getProcessedBytes();

  /**
   * <pre>
   * Estimate of the number of bytes to process.
   * </pre>
   *
   * <code>int64 total_estimated_bytes = 4;</code>
   */
  long getTotalEstimatedBytes();

  /**
   * <code>repeated .google.privacy.dlp.v2beta1.InfoTypeStatistics info_type_stats = 2;</code>
   */
  java.util.List<com.google.privacy.dlp.v2beta1.InfoTypeStatistics> 
      getInfoTypeStatsList();
  /**
   * <code>repeated .google.privacy.dlp.v2beta1.InfoTypeStatistics info_type_stats = 2;</code>
   */
  com.google.privacy.dlp.v2beta1.InfoTypeStatistics getInfoTypeStats(int index);
  /**
   * <code>repeated .google.privacy.dlp.v2beta1.InfoTypeStatistics info_type_stats = 2;</code>
   */
  int getInfoTypeStatsCount();
  /**
   * <code>repeated .google.privacy.dlp.v2beta1.InfoTypeStatistics info_type_stats = 2;</code>
   */
  java.util.List<? extends com.google.privacy.dlp.v2beta1.InfoTypeStatisticsOrBuilder> 
      getInfoTypeStatsOrBuilderList();
  /**
   * <code>repeated .google.privacy.dlp.v2beta1.InfoTypeStatistics info_type_stats = 2;</code>
   */
  com.google.privacy.dlp.v2beta1.InfoTypeStatisticsOrBuilder getInfoTypeStatsOrBuilder(
      int index);

  /**
   * <pre>
   * The time which this request was started.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 3;</code>
   */
  boolean hasCreateTime();
  /**
   * <pre>
   * The time which this request was started.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 3;</code>
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <pre>
   * The time which this request was started.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();
}
