// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/ml/v1beta1/job_service.proto

package com.google.cloud.ml.api.v1beta1;

/**
 * <pre>
 * Represents input parameters for a prediction job.
 * </pre>
 *
 * Protobuf type {@code google.cloud.ml.v1beta1.PredictionInput}
 */
public  final class PredictionInput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.cloud.ml.v1beta1.PredictionInput)
    PredictionInputOrBuilder {
  // Use PredictionInput.newBuilder() to construct.
  private PredictionInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PredictionInput() {
    dataFormat_ = 0;
    inputPaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    outputPath_ = "";
    maxWorkerCount_ = 0L;
    region_ = "";
    runtimeVersion_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PredictionInput(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            modelVersionCase_ = 1;
            modelVersion_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            modelVersionCase_ = 2;
            modelVersion_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            dataFormat_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              inputPaths_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            inputPaths_.add(s);
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            outputPath_ = s;
            break;
          }
          case 48: {

            maxWorkerCount_ = input.readInt64();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            region_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            runtimeVersion_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            modelVersionCase_ = 9;
            modelVersion_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        inputPaths_ = inputPaths_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.ml.api.v1beta1.JobServiceProto.internal_static_google_cloud_ml_v1beta1_PredictionInput_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.ml.api.v1beta1.JobServiceProto.internal_static_google_cloud_ml_v1beta1_PredictionInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.ml.api.v1beta1.PredictionInput.class, com.google.cloud.ml.api.v1beta1.PredictionInput.Builder.class);
  }

  /**
   * <pre>
   * The format used to separate data instances in the source files.
   * </pre>
   *
   * Protobuf enum {@code google.cloud.ml.v1beta1.PredictionInput.DataFormat}
   */
  public enum DataFormat
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Unspecified format.
     * </pre>
     *
     * <code>DATA_FORMAT_UNSPECIFIED = 0;</code>
     */
    DATA_FORMAT_UNSPECIFIED(0),
    /**
     * <pre>
     * The source file is a text file with instances separated by the
     * new-line character.
     * </pre>
     *
     * <code>TEXT = 1;</code>
     */
    TEXT(1),
    /**
     * <pre>
     * The source file is a TFRecord file.
     * </pre>
     *
     * <code>TF_RECORD = 2;</code>
     */
    TF_RECORD(2),
    /**
     * <pre>
     * The source file is a GZIP-compressed TFRecord file.
     * </pre>
     *
     * <code>TF_RECORD_GZIP = 3;</code>
     */
    TF_RECORD_GZIP(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Unspecified format.
     * </pre>
     *
     * <code>DATA_FORMAT_UNSPECIFIED = 0;</code>
     */
    public static final int DATA_FORMAT_UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * The source file is a text file with instances separated by the
     * new-line character.
     * </pre>
     *
     * <code>TEXT = 1;</code>
     */
    public static final int TEXT_VALUE = 1;
    /**
     * <pre>
     * The source file is a TFRecord file.
     * </pre>
     *
     * <code>TF_RECORD = 2;</code>
     */
    public static final int TF_RECORD_VALUE = 2;
    /**
     * <pre>
     * The source file is a GZIP-compressed TFRecord file.
     * </pre>
     *
     * <code>TF_RECORD_GZIP = 3;</code>
     */
    public static final int TF_RECORD_GZIP_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataFormat valueOf(int value) {
      return forNumber(value);
    }

    public static DataFormat forNumber(int value) {
      switch (value) {
        case 0: return DATA_FORMAT_UNSPECIFIED;
        case 1: return TEXT;
        case 2: return TF_RECORD;
        case 3: return TF_RECORD_GZIP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataFormat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataFormat> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataFormat>() {
            public DataFormat findValueByNumber(int number) {
              return DataFormat.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.cloud.ml.api.v1beta1.PredictionInput.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataFormat[] VALUES = values();

    public static DataFormat valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataFormat(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:google.cloud.ml.v1beta1.PredictionInput.DataFormat)
  }

  private int bitField0_;
  private int modelVersionCase_ = 0;
  private java.lang.Object modelVersion_;
  public enum ModelVersionCase
      implements com.google.protobuf.Internal.EnumLite {
    MODEL_NAME(1),
    VERSION_NAME(2),
    URI(9),
    MODELVERSION_NOT_SET(0);
    private final int value;
    private ModelVersionCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ModelVersionCase valueOf(int value) {
      return forNumber(value);
    }

    public static ModelVersionCase forNumber(int value) {
      switch (value) {
        case 1: return MODEL_NAME;
        case 2: return VERSION_NAME;
        case 9: return URI;
        case 0: return MODELVERSION_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ModelVersionCase
  getModelVersionCase() {
    return ModelVersionCase.forNumber(
        modelVersionCase_);
  }

  public static final int MODEL_NAME_FIELD_NUMBER = 1;
  /**
   * <pre>
   * Use this field if you want to use the default version for the specified
   * model. The string must use the following format:
   * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;[YOUR_MODEL]&lt;/var&gt;"`
   * </pre>
   *
   * <code>string model_name = 1;</code>
   */
  public java.lang.String getModelName() {
    java.lang.Object ref = "";
    if (modelVersionCase_ == 1) {
      ref = modelVersion_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (modelVersionCase_ == 1) {
        modelVersion_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Use this field if you want to use the default version for the specified
   * model. The string must use the following format:
   * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;[YOUR_MODEL]&lt;/var&gt;"`
   * </pre>
   *
   * <code>string model_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getModelNameBytes() {
    java.lang.Object ref = "";
    if (modelVersionCase_ == 1) {
      ref = modelVersion_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (modelVersionCase_ == 1) {
        modelVersion_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_NAME_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Use this field if you want to specify a version of the model to use. The
   * string is formatted the same way as `model_version`, with the addition
   * of the version information:
   * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;YOUR_MODEL/versions/&lt;var&gt;[YOUR_VERSION]&lt;/var&gt;"`
   * </pre>
   *
   * <code>string version_name = 2;</code>
   */
  public java.lang.String getVersionName() {
    java.lang.Object ref = "";
    if (modelVersionCase_ == 2) {
      ref = modelVersion_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (modelVersionCase_ == 2) {
        modelVersion_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Use this field if you want to specify a version of the model to use. The
   * string is formatted the same way as `model_version`, with the addition
   * of the version information:
   * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;YOUR_MODEL/versions/&lt;var&gt;[YOUR_VERSION]&lt;/var&gt;"`
   * </pre>
   *
   * <code>string version_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getVersionNameBytes() {
    java.lang.Object ref = "";
    if (modelVersionCase_ == 2) {
      ref = modelVersion_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (modelVersionCase_ == 2) {
        modelVersion_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int URI_FIELD_NUMBER = 9;
  /**
   * <pre>
   * Use this field if you want to specify a Google Cloud Storage path for
   * the model to use.
   * </pre>
   *
   * <code>string uri = 9;</code>
   */
  public java.lang.String getUri() {
    java.lang.Object ref = "";
    if (modelVersionCase_ == 9) {
      ref = modelVersion_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (modelVersionCase_ == 9) {
        modelVersion_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Use this field if you want to specify a Google Cloud Storage path for
   * the model to use.
   * </pre>
   *
   * <code>string uri = 9;</code>
   */
  public com.google.protobuf.ByteString
      getUriBytes() {
    java.lang.Object ref = "";
    if (modelVersionCase_ == 9) {
      ref = modelVersion_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (modelVersionCase_ == 9) {
        modelVersion_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FORMAT_FIELD_NUMBER = 3;
  private int dataFormat_;
  /**
   * <pre>
   * Required. The format of the input data files.
   * </pre>
   *
   * <code>.google.cloud.ml.v1beta1.PredictionInput.DataFormat data_format = 3;</code>
   */
  public int getDataFormatValue() {
    return dataFormat_;
  }
  /**
   * <pre>
   * Required. The format of the input data files.
   * </pre>
   *
   * <code>.google.cloud.ml.v1beta1.PredictionInput.DataFormat data_format = 3;</code>
   */
  public com.google.cloud.ml.api.v1beta1.PredictionInput.DataFormat getDataFormat() {
    com.google.cloud.ml.api.v1beta1.PredictionInput.DataFormat result = com.google.cloud.ml.api.v1beta1.PredictionInput.DataFormat.valueOf(dataFormat_);
    return result == null ? com.google.cloud.ml.api.v1beta1.PredictionInput.DataFormat.UNRECOGNIZED : result;
  }

  public static final int INPUT_PATHS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList inputPaths_;
  /**
   * <pre>
   * Required. The Google Cloud Storage location of the input data files.
   * May contain wildcards.
   * </pre>
   *
   * <code>repeated string input_paths = 4;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getInputPathsList() {
    return inputPaths_;
  }
  /**
   * <pre>
   * Required. The Google Cloud Storage location of the input data files.
   * May contain wildcards.
   * </pre>
   *
   * <code>repeated string input_paths = 4;</code>
   */
  public int getInputPathsCount() {
    return inputPaths_.size();
  }
  /**
   * <pre>
   * Required. The Google Cloud Storage location of the input data files.
   * May contain wildcards.
   * </pre>
   *
   * <code>repeated string input_paths = 4;</code>
   */
  public java.lang.String getInputPaths(int index) {
    return inputPaths_.get(index);
  }
  /**
   * <pre>
   * Required. The Google Cloud Storage location of the input data files.
   * May contain wildcards.
   * </pre>
   *
   * <code>repeated string input_paths = 4;</code>
   */
  public com.google.protobuf.ByteString
      getInputPathsBytes(int index) {
    return inputPaths_.getByteString(index);
  }

  public static final int OUTPUT_PATH_FIELD_NUMBER = 5;
  private volatile java.lang.Object outputPath_;
  /**
   * <pre>
   * Required. The output Google Cloud Storage location.
   * </pre>
   *
   * <code>string output_path = 5;</code>
   */
  public java.lang.String getOutputPath() {
    java.lang.Object ref = outputPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outputPath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. The output Google Cloud Storage location.
   * </pre>
   *
   * <code>string output_path = 5;</code>
   */
  public com.google.protobuf.ByteString
      getOutputPathBytes() {
    java.lang.Object ref = outputPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outputPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAX_WORKER_COUNT_FIELD_NUMBER = 6;
  private long maxWorkerCount_;
  /**
   * <pre>
   * Optional. The maximum number of workers to be used for parallel processing.
   * Defaults to 10 if not specified.
   * </pre>
   *
   * <code>int64 max_worker_count = 6;</code>
   */
  public long getMaxWorkerCount() {
    return maxWorkerCount_;
  }

  public static final int REGION_FIELD_NUMBER = 7;
  private volatile java.lang.Object region_;
  /**
   * <pre>
   * Required. The Google Compute Engine region to run the prediction job in.
   * </pre>
   *
   * <code>string region = 7;</code>
   */
  public java.lang.String getRegion() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      region_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. The Google Compute Engine region to run the prediction job in.
   * </pre>
   *
   * <code>string region = 7;</code>
   */
  public com.google.protobuf.ByteString
      getRegionBytes() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      region_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RUNTIME_VERSION_FIELD_NUMBER = 8;
  private volatile java.lang.Object runtimeVersion_;
  /**
   * <pre>
   * Optional. The Google Cloud ML runtime version to use for this batch
   * prediction. If not set, Google Cloud ML will pick the runtime version used
   * during the CreateVersion request for this model version, or choose the
   * latest stable version when model version information is not available
   * such as when the model is specified by uri.
   * </pre>
   *
   * <code>string runtime_version = 8;</code>
   */
  public java.lang.String getRuntimeVersion() {
    java.lang.Object ref = runtimeVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      runtimeVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional. The Google Cloud ML runtime version to use for this batch
   * prediction. If not set, Google Cloud ML will pick the runtime version used
   * during the CreateVersion request for this model version, or choose the
   * latest stable version when model version information is not available
   * such as when the model is specified by uri.
   * </pre>
   *
   * <code>string runtime_version = 8;</code>
   */
  public com.google.protobuf.ByteString
      getRuntimeVersionBytes() {
    java.lang.Object ref = runtimeVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      runtimeVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (modelVersionCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, modelVersion_);
    }
    if (modelVersionCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, modelVersion_);
    }
    if (dataFormat_ != com.google.cloud.ml.api.v1beta1.PredictionInput.DataFormat.DATA_FORMAT_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, dataFormat_);
    }
    for (int i = 0; i < inputPaths_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, inputPaths_.getRaw(i));
    }
    if (!getOutputPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, outputPath_);
    }
    if (maxWorkerCount_ != 0L) {
      output.writeInt64(6, maxWorkerCount_);
    }
    if (!getRegionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, region_);
    }
    if (!getRuntimeVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, runtimeVersion_);
    }
    if (modelVersionCase_ == 9) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, modelVersion_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (modelVersionCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, modelVersion_);
    }
    if (modelVersionCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, modelVersion_);
    }
    if (dataFormat_ != com.google.cloud.ml.api.v1beta1.PredictionInput.DataFormat.DATA_FORMAT_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, dataFormat_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < inputPaths_.size(); i++) {
        dataSize += computeStringSizeNoTag(inputPaths_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInputPathsList().size();
    }
    if (!getOutputPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, outputPath_);
    }
    if (maxWorkerCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, maxWorkerCount_);
    }
    if (!getRegionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, region_);
    }
    if (!getRuntimeVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, runtimeVersion_);
    }
    if (modelVersionCase_ == 9) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, modelVersion_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.ml.api.v1beta1.PredictionInput)) {
      return super.equals(obj);
    }
    com.google.cloud.ml.api.v1beta1.PredictionInput other = (com.google.cloud.ml.api.v1beta1.PredictionInput) obj;

    boolean result = true;
    result = result && dataFormat_ == other.dataFormat_;
    result = result && getInputPathsList()
        .equals(other.getInputPathsList());
    result = result && getOutputPath()
        .equals(other.getOutputPath());
    result = result && (getMaxWorkerCount()
        == other.getMaxWorkerCount());
    result = result && getRegion()
        .equals(other.getRegion());
    result = result && getRuntimeVersion()
        .equals(other.getRuntimeVersion());
    result = result && getModelVersionCase().equals(
        other.getModelVersionCase());
    if (!result) return false;
    switch (modelVersionCase_) {
      case 1:
        result = result && getModelName()
            .equals(other.getModelName());
        break;
      case 2:
        result = result && getVersionName()
            .equals(other.getVersionName());
        break;
      case 9:
        result = result && getUri()
            .equals(other.getUri());
        break;
      case 0:
      default:
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATA_FORMAT_FIELD_NUMBER;
    hash = (53 * hash) + dataFormat_;
    if (getInputPathsCount() > 0) {
      hash = (37 * hash) + INPUT_PATHS_FIELD_NUMBER;
      hash = (53 * hash) + getInputPathsList().hashCode();
    }
    hash = (37 * hash) + OUTPUT_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getOutputPath().hashCode();
    hash = (37 * hash) + MAX_WORKER_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxWorkerCount());
    hash = (37 * hash) + REGION_FIELD_NUMBER;
    hash = (53 * hash) + getRegion().hashCode();
    hash = (37 * hash) + RUNTIME_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getRuntimeVersion().hashCode();
    switch (modelVersionCase_) {
      case 1:
        hash = (37 * hash) + MODEL_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getModelName().hashCode();
        break;
      case 2:
        hash = (37 * hash) + VERSION_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getVersionName().hashCode();
        break;
      case 9:
        hash = (37 * hash) + URI_FIELD_NUMBER;
        hash = (53 * hash) + getUri().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.ml.api.v1beta1.PredictionInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.ml.api.v1beta1.PredictionInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.ml.api.v1beta1.PredictionInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.ml.api.v1beta1.PredictionInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.ml.api.v1beta1.PredictionInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.ml.api.v1beta1.PredictionInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.ml.api.v1beta1.PredictionInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.cloud.ml.api.v1beta1.PredictionInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.ml.api.v1beta1.PredictionInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.ml.api.v1beta1.PredictionInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.ml.api.v1beta1.PredictionInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents input parameters for a prediction job.
   * </pre>
   *
   * Protobuf type {@code google.cloud.ml.v1beta1.PredictionInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.cloud.ml.v1beta1.PredictionInput)
      com.google.cloud.ml.api.v1beta1.PredictionInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.ml.api.v1beta1.JobServiceProto.internal_static_google_cloud_ml_v1beta1_PredictionInput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.ml.api.v1beta1.JobServiceProto.internal_static_google_cloud_ml_v1beta1_PredictionInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.ml.api.v1beta1.PredictionInput.class, com.google.cloud.ml.api.v1beta1.PredictionInput.Builder.class);
    }

    // Construct using com.google.cloud.ml.api.v1beta1.PredictionInput.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dataFormat_ = 0;

      inputPaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      outputPath_ = "";

      maxWorkerCount_ = 0L;

      region_ = "";

      runtimeVersion_ = "";

      modelVersionCase_ = 0;
      modelVersion_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.ml.api.v1beta1.JobServiceProto.internal_static_google_cloud_ml_v1beta1_PredictionInput_descriptor;
    }

    public com.google.cloud.ml.api.v1beta1.PredictionInput getDefaultInstanceForType() {
      return com.google.cloud.ml.api.v1beta1.PredictionInput.getDefaultInstance();
    }

    public com.google.cloud.ml.api.v1beta1.PredictionInput build() {
      com.google.cloud.ml.api.v1beta1.PredictionInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.cloud.ml.api.v1beta1.PredictionInput buildPartial() {
      com.google.cloud.ml.api.v1beta1.PredictionInput result = new com.google.cloud.ml.api.v1beta1.PredictionInput(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (modelVersionCase_ == 1) {
        result.modelVersion_ = modelVersion_;
      }
      if (modelVersionCase_ == 2) {
        result.modelVersion_ = modelVersion_;
      }
      if (modelVersionCase_ == 9) {
        result.modelVersion_ = modelVersion_;
      }
      result.dataFormat_ = dataFormat_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        inputPaths_ = inputPaths_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.inputPaths_ = inputPaths_;
      result.outputPath_ = outputPath_;
      result.maxWorkerCount_ = maxWorkerCount_;
      result.region_ = region_;
      result.runtimeVersion_ = runtimeVersion_;
      result.bitField0_ = to_bitField0_;
      result.modelVersionCase_ = modelVersionCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.ml.api.v1beta1.PredictionInput) {
        return mergeFrom((com.google.cloud.ml.api.v1beta1.PredictionInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.ml.api.v1beta1.PredictionInput other) {
      if (other == com.google.cloud.ml.api.v1beta1.PredictionInput.getDefaultInstance()) return this;
      if (other.dataFormat_ != 0) {
        setDataFormatValue(other.getDataFormatValue());
      }
      if (!other.inputPaths_.isEmpty()) {
        if (inputPaths_.isEmpty()) {
          inputPaths_ = other.inputPaths_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureInputPathsIsMutable();
          inputPaths_.addAll(other.inputPaths_);
        }
        onChanged();
      }
      if (!other.getOutputPath().isEmpty()) {
        outputPath_ = other.outputPath_;
        onChanged();
      }
      if (other.getMaxWorkerCount() != 0L) {
        setMaxWorkerCount(other.getMaxWorkerCount());
      }
      if (!other.getRegion().isEmpty()) {
        region_ = other.region_;
        onChanged();
      }
      if (!other.getRuntimeVersion().isEmpty()) {
        runtimeVersion_ = other.runtimeVersion_;
        onChanged();
      }
      switch (other.getModelVersionCase()) {
        case MODEL_NAME: {
          modelVersionCase_ = 1;
          modelVersion_ = other.modelVersion_;
          onChanged();
          break;
        }
        case VERSION_NAME: {
          modelVersionCase_ = 2;
          modelVersion_ = other.modelVersion_;
          onChanged();
          break;
        }
        case URI: {
          modelVersionCase_ = 9;
          modelVersion_ = other.modelVersion_;
          onChanged();
          break;
        }
        case MODELVERSION_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.ml.api.v1beta1.PredictionInput parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.ml.api.v1beta1.PredictionInput) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int modelVersionCase_ = 0;
    private java.lang.Object modelVersion_;
    public ModelVersionCase
        getModelVersionCase() {
      return ModelVersionCase.forNumber(
          modelVersionCase_);
    }

    public Builder clearModelVersion() {
      modelVersionCase_ = 0;
      modelVersion_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <pre>
     * Use this field if you want to use the default version for the specified
     * model. The string must use the following format:
     * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;[YOUR_MODEL]&lt;/var&gt;"`
     * </pre>
     *
     * <code>string model_name = 1;</code>
     */
    public java.lang.String getModelName() {
      java.lang.Object ref = "";
      if (modelVersionCase_ == 1) {
        ref = modelVersion_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (modelVersionCase_ == 1) {
          modelVersion_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Use this field if you want to use the default version for the specified
     * model. The string must use the following format:
     * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;[YOUR_MODEL]&lt;/var&gt;"`
     * </pre>
     *
     * <code>string model_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      java.lang.Object ref = "";
      if (modelVersionCase_ == 1) {
        ref = modelVersion_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (modelVersionCase_ == 1) {
          modelVersion_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Use this field if you want to use the default version for the specified
     * model. The string must use the following format:
     * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;[YOUR_MODEL]&lt;/var&gt;"`
     * </pre>
     *
     * <code>string model_name = 1;</code>
     */
    public Builder setModelName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  modelVersionCase_ = 1;
      modelVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Use this field if you want to use the default version for the specified
     * model. The string must use the following format:
     * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;[YOUR_MODEL]&lt;/var&gt;"`
     * </pre>
     *
     * <code>string model_name = 1;</code>
     */
    public Builder clearModelName() {
      if (modelVersionCase_ == 1) {
        modelVersionCase_ = 0;
        modelVersion_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Use this field if you want to use the default version for the specified
     * model. The string must use the following format:
     * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;[YOUR_MODEL]&lt;/var&gt;"`
     * </pre>
     *
     * <code>string model_name = 1;</code>
     */
    public Builder setModelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      modelVersionCase_ = 1;
      modelVersion_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Use this field if you want to specify a version of the model to use. The
     * string is formatted the same way as `model_version`, with the addition
     * of the version information:
     * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;YOUR_MODEL/versions/&lt;var&gt;[YOUR_VERSION]&lt;/var&gt;"`
     * </pre>
     *
     * <code>string version_name = 2;</code>
     */
    public java.lang.String getVersionName() {
      java.lang.Object ref = "";
      if (modelVersionCase_ == 2) {
        ref = modelVersion_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (modelVersionCase_ == 2) {
          modelVersion_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Use this field if you want to specify a version of the model to use. The
     * string is formatted the same way as `model_version`, with the addition
     * of the version information:
     * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;YOUR_MODEL/versions/&lt;var&gt;[YOUR_VERSION]&lt;/var&gt;"`
     * </pre>
     *
     * <code>string version_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionNameBytes() {
      java.lang.Object ref = "";
      if (modelVersionCase_ == 2) {
        ref = modelVersion_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (modelVersionCase_ == 2) {
          modelVersion_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Use this field if you want to specify a version of the model to use. The
     * string is formatted the same way as `model_version`, with the addition
     * of the version information:
     * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;YOUR_MODEL/versions/&lt;var&gt;[YOUR_VERSION]&lt;/var&gt;"`
     * </pre>
     *
     * <code>string version_name = 2;</code>
     */
    public Builder setVersionName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  modelVersionCase_ = 2;
      modelVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Use this field if you want to specify a version of the model to use. The
     * string is formatted the same way as `model_version`, with the addition
     * of the version information:
     * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;YOUR_MODEL/versions/&lt;var&gt;[YOUR_VERSION]&lt;/var&gt;"`
     * </pre>
     *
     * <code>string version_name = 2;</code>
     */
    public Builder clearVersionName() {
      if (modelVersionCase_ == 2) {
        modelVersionCase_ = 0;
        modelVersion_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Use this field if you want to specify a version of the model to use. The
     * string is formatted the same way as `model_version`, with the addition
     * of the version information:
     * `"projects/&lt;var&gt;[YOUR_PROJECT]&lt;/var&gt;/models/&lt;var&gt;YOUR_MODEL/versions/&lt;var&gt;[YOUR_VERSION]&lt;/var&gt;"`
     * </pre>
     *
     * <code>string version_name = 2;</code>
     */
    public Builder setVersionNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      modelVersionCase_ = 2;
      modelVersion_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Use this field if you want to specify a Google Cloud Storage path for
     * the model to use.
     * </pre>
     *
     * <code>string uri = 9;</code>
     */
    public java.lang.String getUri() {
      java.lang.Object ref = "";
      if (modelVersionCase_ == 9) {
        ref = modelVersion_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (modelVersionCase_ == 9) {
          modelVersion_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Use this field if you want to specify a Google Cloud Storage path for
     * the model to use.
     * </pre>
     *
     * <code>string uri = 9;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = "";
      if (modelVersionCase_ == 9) {
        ref = modelVersion_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (modelVersionCase_ == 9) {
          modelVersion_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Use this field if you want to specify a Google Cloud Storage path for
     * the model to use.
     * </pre>
     *
     * <code>string uri = 9;</code>
     */
    public Builder setUri(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  modelVersionCase_ = 9;
      modelVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Use this field if you want to specify a Google Cloud Storage path for
     * the model to use.
     * </pre>
     *
     * <code>string uri = 9;</code>
     */
    public Builder clearUri() {
      if (modelVersionCase_ == 9) {
        modelVersionCase_ = 0;
        modelVersion_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Use this field if you want to specify a Google Cloud Storage path for
     * the model to use.
     * </pre>
     *
     * <code>string uri = 9;</code>
     */
    public Builder setUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      modelVersionCase_ = 9;
      modelVersion_ = value;
      onChanged();
      return this;
    }

    private int dataFormat_ = 0;
    /**
     * <pre>
     * Required. The format of the input data files.
     * </pre>
     *
     * <code>.google.cloud.ml.v1beta1.PredictionInput.DataFormat data_format = 3;</code>
     */
    public int getDataFormatValue() {
      return dataFormat_;
    }
    /**
     * <pre>
     * Required. The format of the input data files.
     * </pre>
     *
     * <code>.google.cloud.ml.v1beta1.PredictionInput.DataFormat data_format = 3;</code>
     */
    public Builder setDataFormatValue(int value) {
      dataFormat_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The format of the input data files.
     * </pre>
     *
     * <code>.google.cloud.ml.v1beta1.PredictionInput.DataFormat data_format = 3;</code>
     */
    public com.google.cloud.ml.api.v1beta1.PredictionInput.DataFormat getDataFormat() {
      com.google.cloud.ml.api.v1beta1.PredictionInput.DataFormat result = com.google.cloud.ml.api.v1beta1.PredictionInput.DataFormat.valueOf(dataFormat_);
      return result == null ? com.google.cloud.ml.api.v1beta1.PredictionInput.DataFormat.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Required. The format of the input data files.
     * </pre>
     *
     * <code>.google.cloud.ml.v1beta1.PredictionInput.DataFormat data_format = 3;</code>
     */
    public Builder setDataFormat(com.google.cloud.ml.api.v1beta1.PredictionInput.DataFormat value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      dataFormat_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The format of the input data files.
     * </pre>
     *
     * <code>.google.cloud.ml.v1beta1.PredictionInput.DataFormat data_format = 3;</code>
     */
    public Builder clearDataFormat() {
      
      dataFormat_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList inputPaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureInputPathsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        inputPaths_ = new com.google.protobuf.LazyStringArrayList(inputPaths_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <pre>
     * Required. The Google Cloud Storage location of the input data files.
     * May contain wildcards.
     * </pre>
     *
     * <code>repeated string input_paths = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInputPathsList() {
      return inputPaths_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Required. The Google Cloud Storage location of the input data files.
     * May contain wildcards.
     * </pre>
     *
     * <code>repeated string input_paths = 4;</code>
     */
    public int getInputPathsCount() {
      return inputPaths_.size();
    }
    /**
     * <pre>
     * Required. The Google Cloud Storage location of the input data files.
     * May contain wildcards.
     * </pre>
     *
     * <code>repeated string input_paths = 4;</code>
     */
    public java.lang.String getInputPaths(int index) {
      return inputPaths_.get(index);
    }
    /**
     * <pre>
     * Required. The Google Cloud Storage location of the input data files.
     * May contain wildcards.
     * </pre>
     *
     * <code>repeated string input_paths = 4;</code>
     */
    public com.google.protobuf.ByteString
        getInputPathsBytes(int index) {
      return inputPaths_.getByteString(index);
    }
    /**
     * <pre>
     * Required. The Google Cloud Storage location of the input data files.
     * May contain wildcards.
     * </pre>
     *
     * <code>repeated string input_paths = 4;</code>
     */
    public Builder setInputPaths(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInputPathsIsMutable();
      inputPaths_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The Google Cloud Storage location of the input data files.
     * May contain wildcards.
     * </pre>
     *
     * <code>repeated string input_paths = 4;</code>
     */
    public Builder addInputPaths(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInputPathsIsMutable();
      inputPaths_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The Google Cloud Storage location of the input data files.
     * May contain wildcards.
     * </pre>
     *
     * <code>repeated string input_paths = 4;</code>
     */
    public Builder addAllInputPaths(
        java.lang.Iterable<java.lang.String> values) {
      ensureInputPathsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, inputPaths_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The Google Cloud Storage location of the input data files.
     * May contain wildcards.
     * </pre>
     *
     * <code>repeated string input_paths = 4;</code>
     */
    public Builder clearInputPaths() {
      inputPaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The Google Cloud Storage location of the input data files.
     * May contain wildcards.
     * </pre>
     *
     * <code>repeated string input_paths = 4;</code>
     */
    public Builder addInputPathsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureInputPathsIsMutable();
      inputPaths_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object outputPath_ = "";
    /**
     * <pre>
     * Required. The output Google Cloud Storage location.
     * </pre>
     *
     * <code>string output_path = 5;</code>
     */
    public java.lang.String getOutputPath() {
      java.lang.Object ref = outputPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. The output Google Cloud Storage location.
     * </pre>
     *
     * <code>string output_path = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOutputPathBytes() {
      java.lang.Object ref = outputPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. The output Google Cloud Storage location.
     * </pre>
     *
     * <code>string output_path = 5;</code>
     */
    public Builder setOutputPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      outputPath_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The output Google Cloud Storage location.
     * </pre>
     *
     * <code>string output_path = 5;</code>
     */
    public Builder clearOutputPath() {
      
      outputPath_ = getDefaultInstance().getOutputPath();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The output Google Cloud Storage location.
     * </pre>
     *
     * <code>string output_path = 5;</code>
     */
    public Builder setOutputPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      outputPath_ = value;
      onChanged();
      return this;
    }

    private long maxWorkerCount_ ;
    /**
     * <pre>
     * Optional. The maximum number of workers to be used for parallel processing.
     * Defaults to 10 if not specified.
     * </pre>
     *
     * <code>int64 max_worker_count = 6;</code>
     */
    public long getMaxWorkerCount() {
      return maxWorkerCount_;
    }
    /**
     * <pre>
     * Optional. The maximum number of workers to be used for parallel processing.
     * Defaults to 10 if not specified.
     * </pre>
     *
     * <code>int64 max_worker_count = 6;</code>
     */
    public Builder setMaxWorkerCount(long value) {
      
      maxWorkerCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The maximum number of workers to be used for parallel processing.
     * Defaults to 10 if not specified.
     * </pre>
     *
     * <code>int64 max_worker_count = 6;</code>
     */
    public Builder clearMaxWorkerCount() {
      
      maxWorkerCount_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object region_ = "";
    /**
     * <pre>
     * Required. The Google Compute Engine region to run the prediction job in.
     * </pre>
     *
     * <code>string region = 7;</code>
     */
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        region_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. The Google Compute Engine region to run the prediction job in.
     * </pre>
     *
     * <code>string region = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. The Google Compute Engine region to run the prediction job in.
     * </pre>
     *
     * <code>string region = 7;</code>
     */
    public Builder setRegion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      region_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The Google Compute Engine region to run the prediction job in.
     * </pre>
     *
     * <code>string region = 7;</code>
     */
    public Builder clearRegion() {
      
      region_ = getDefaultInstance().getRegion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The Google Compute Engine region to run the prediction job in.
     * </pre>
     *
     * <code>string region = 7;</code>
     */
    public Builder setRegionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      region_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object runtimeVersion_ = "";
    /**
     * <pre>
     * Optional. The Google Cloud ML runtime version to use for this batch
     * prediction. If not set, Google Cloud ML will pick the runtime version used
     * during the CreateVersion request for this model version, or choose the
     * latest stable version when model version information is not available
     * such as when the model is specified by uri.
     * </pre>
     *
     * <code>string runtime_version = 8;</code>
     */
    public java.lang.String getRuntimeVersion() {
      java.lang.Object ref = runtimeVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        runtimeVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional. The Google Cloud ML runtime version to use for this batch
     * prediction. If not set, Google Cloud ML will pick the runtime version used
     * during the CreateVersion request for this model version, or choose the
     * latest stable version when model version information is not available
     * such as when the model is specified by uri.
     * </pre>
     *
     * <code>string runtime_version = 8;</code>
     */
    public com.google.protobuf.ByteString
        getRuntimeVersionBytes() {
      java.lang.Object ref = runtimeVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runtimeVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional. The Google Cloud ML runtime version to use for this batch
     * prediction. If not set, Google Cloud ML will pick the runtime version used
     * during the CreateVersion request for this model version, or choose the
     * latest stable version when model version information is not available
     * such as when the model is specified by uri.
     * </pre>
     *
     * <code>string runtime_version = 8;</code>
     */
    public Builder setRuntimeVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      runtimeVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The Google Cloud ML runtime version to use for this batch
     * prediction. If not set, Google Cloud ML will pick the runtime version used
     * during the CreateVersion request for this model version, or choose the
     * latest stable version when model version information is not available
     * such as when the model is specified by uri.
     * </pre>
     *
     * <code>string runtime_version = 8;</code>
     */
    public Builder clearRuntimeVersion() {
      
      runtimeVersion_ = getDefaultInstance().getRuntimeVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The Google Cloud ML runtime version to use for this batch
     * prediction. If not set, Google Cloud ML will pick the runtime version used
     * during the CreateVersion request for this model version, or choose the
     * latest stable version when model version information is not available
     * such as when the model is specified by uri.
     * </pre>
     *
     * <code>string runtime_version = 8;</code>
     */
    public Builder setRuntimeVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      runtimeVersion_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.cloud.ml.v1beta1.PredictionInput)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.ml.v1beta1.PredictionInput)
  private static final com.google.cloud.ml.api.v1beta1.PredictionInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.ml.api.v1beta1.PredictionInput();
  }

  public static com.google.cloud.ml.api.v1beta1.PredictionInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PredictionInput>
      PARSER = new com.google.protobuf.AbstractParser<PredictionInput>() {
    public PredictionInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PredictionInput(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PredictionInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PredictionInput> getParserForType() {
    return PARSER;
  }

  public com.google.cloud.ml.api.v1beta1.PredictionInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

