// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/clouddebugger/v2/controller.proto

package com.google.devtools.clouddebugger.v2;

public final class ControllerProto {
  private ControllerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_RegisterDebuggeeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_RegisterDebuggeeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_RegisterDebuggeeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_RegisterDebuggeeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_ListActiveBreakpointsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_ListActiveBreakpointsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_ListActiveBreakpointsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_ListActiveBreakpointsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_UpdateActiveBreakpointRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_UpdateActiveBreakpointRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_UpdateActiveBreakpointResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_UpdateActiveBreakpointResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1google/devtools/clouddebugger/v2/contr" +
      "oller.proto\022 google.devtools.clouddebugg" +
      "er.v2\032\034google/api/annotations.proto\032+goo" +
      "gle/devtools/clouddebugger/v2/data.proto" +
      "\032\033google/protobuf/empty.proto\"W\n\027Registe" +
      "rDebuggeeRequest\022<\n\010debuggee\030\001 \001(\0132*.goo" +
      "gle.devtools.clouddebugger.v2.Debuggee\"X" +
      "\n\030RegisterDebuggeeResponse\022<\n\010debuggee\030\001" +
      " \001(\0132*.google.devtools.clouddebugger.v2." +
      "Debuggee\"c\n\034ListActiveBreakpointsRequest",
      "\022\023\n\013debuggee_id\030\001 \001(\t\022\022\n\nwait_token\030\002 \001(" +
      "\t\022\032\n\022success_on_timeout\030\003 \001(\010\"\221\001\n\035ListAc" +
      "tiveBreakpointsResponse\022A\n\013breakpoints\030\001" +
      " \003(\0132,.google.devtools.clouddebugger.v2." +
      "Breakpoint\022\027\n\017next_wait_token\030\002 \001(\t\022\024\n\014w" +
      "ait_expired\030\003 \001(\010\"v\n\035UpdateActiveBreakpo" +
      "intRequest\022\023\n\013debuggee_id\030\001 \001(\t\022@\n\nbreak" +
      "point\030\002 \001(\0132,.google.devtools.clouddebug" +
      "ger.v2.Breakpoint\" \n\036UpdateActiveBreakpo" +
      "intResponse2\213\005\n\013Controller2\022\267\001\n\020Register",
      "Debuggee\0229.google.devtools.clouddebugger" +
      ".v2.RegisterDebuggeeRequest\032:.google.dev" +
      "tools.clouddebugger.v2.RegisterDebuggeeR" +
      "esponse\",\202\323\344\223\002&\"!/v2/controller/debuggee" +
      "s/register:\001*\022\324\001\n\025ListActiveBreakpoints\022" +
      ">.google.devtools.clouddebugger.v2.ListA" +
      "ctiveBreakpointsRequest\032?.google.devtool" +
      "s.clouddebugger.v2.ListActiveBreakpoints" +
      "Response\":\202\323\344\223\0024\0222/v2/controller/debugge" +
      "es/{debuggee_id}/breakpoints\022\352\001\n\026UpdateA",
      "ctiveBreakpoint\022?.google.devtools.cloudd" +
      "ebugger.v2.UpdateActiveBreakpointRequest" +
      "\032@.google.devtools.clouddebugger.v2.Upda" +
      "teActiveBreakpointResponse\"M\202\323\344\223\002G\032B/v2/" +
      "controller/debuggees/{debuggee_id}/break" +
      "points/{breakpoint.id}:\001*B\210\001\n$com.google" +
      ".devtools.clouddebugger.v2B\017ControllerPr" +
      "otoP\001ZMgoogle.golang.org/genproto/google" +
      "apis/devtools/clouddebugger/v2;clouddebu" +
      "ggerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.devtools.clouddebugger.v2.DataProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_google_devtools_clouddebugger_v2_RegisterDebuggeeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_devtools_clouddebugger_v2_RegisterDebuggeeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_RegisterDebuggeeRequest_descriptor,
        new java.lang.String[] { "Debuggee", });
    internal_static_google_devtools_clouddebugger_v2_RegisterDebuggeeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_devtools_clouddebugger_v2_RegisterDebuggeeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_RegisterDebuggeeResponse_descriptor,
        new java.lang.String[] { "Debuggee", });
    internal_static_google_devtools_clouddebugger_v2_ListActiveBreakpointsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_devtools_clouddebugger_v2_ListActiveBreakpointsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_ListActiveBreakpointsRequest_descriptor,
        new java.lang.String[] { "DebuggeeId", "WaitToken", "SuccessOnTimeout", });
    internal_static_google_devtools_clouddebugger_v2_ListActiveBreakpointsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_devtools_clouddebugger_v2_ListActiveBreakpointsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_ListActiveBreakpointsResponse_descriptor,
        new java.lang.String[] { "Breakpoints", "NextWaitToken", "WaitExpired", });
    internal_static_google_devtools_clouddebugger_v2_UpdateActiveBreakpointRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_devtools_clouddebugger_v2_UpdateActiveBreakpointRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_UpdateActiveBreakpointRequest_descriptor,
        new java.lang.String[] { "DebuggeeId", "Breakpoint", });
    internal_static_google_devtools_clouddebugger_v2_UpdateActiveBreakpointResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_devtools_clouddebugger_v2_UpdateActiveBreakpointResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_UpdateActiveBreakpointResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.devtools.clouddebugger.v2.DataProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
