// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/clouddebugger/v2/debugger.proto

package com.google.devtools.clouddebugger.v2;

public final class DebuggerProto {
  private DebuggerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_SetBreakpointRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_SetBreakpointRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_SetBreakpointResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_SetBreakpointResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_GetBreakpointRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_GetBreakpointRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_GetBreakpointResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_GetBreakpointResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_DeleteBreakpointRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_DeleteBreakpointRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_ListBreakpointsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_ListBreakpointsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_ListBreakpointsRequest_BreakpointActionValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_ListBreakpointsRequest_BreakpointActionValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_ListBreakpointsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_ListBreakpointsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_ListDebuggeesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_ListDebuggeesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_clouddebugger_v2_ListDebuggeesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_clouddebugger_v2_ListDebuggeesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/google/devtools/clouddebugger/v2/debug" +
      "ger.proto\022 google.devtools.clouddebugger" +
      ".v2\032\034google/api/annotations.proto\032+googl" +
      "e/devtools/clouddebugger/v2/data.proto\032\033" +
      "google/protobuf/empty.proto\"\205\001\n\024SetBreak" +
      "pointRequest\022\023\n\013debuggee_id\030\001 \001(\t\022@\n\nbre" +
      "akpoint\030\002 \001(\0132,.google.devtools.clouddeb" +
      "ugger.v2.Breakpoint\022\026\n\016client_version\030\004 " +
      "\001(\t\"Y\n\025SetBreakpointResponse\022@\n\nbreakpoi" +
      "nt\030\001 \001(\0132,.google.devtools.clouddebugger",
      ".v2.Breakpoint\"Z\n\024GetBreakpointRequest\022\023" +
      "\n\013debuggee_id\030\001 \001(\t\022\025\n\rbreakpoint_id\030\002 \001" +
      "(\t\022\026\n\016client_version\030\004 \001(\t\"Y\n\025GetBreakpo" +
      "intResponse\022@\n\nbreakpoint\030\001 \001(\0132,.google" +
      ".devtools.clouddebugger.v2.Breakpoint\"]\n" +
      "\027DeleteBreakpointRequest\022\023\n\013debuggee_id\030" +
      "\001 \001(\t\022\025\n\rbreakpoint_id\030\002 \001(\t\022\026\n\016client_v" +
      "ersion\030\003 \001(\t\"\342\002\n\026ListBreakpointsRequest\022" +
      "\023\n\013debuggee_id\030\001 \001(\t\022\031\n\021include_all_user" +
      "s\030\002 \001(\010\022\030\n\020include_inactive\030\003 \001(\010\022^\n\006act",
      "ion\030\004 \001(\0132N.google.devtools.clouddebugge" +
      "r.v2.ListBreakpointsRequest.BreakpointAc" +
      "tionValue\022\025\n\rstrip_results\030\005 \001(\010\022\022\n\nwait" +
      "_token\030\006 \001(\t\022\026\n\016client_version\030\010 \001(\t\032[\n\025" +
      "BreakpointActionValue\022B\n\005value\030\001 \001(\01623.g" +
      "oogle.devtools.clouddebugger.v2.Breakpoi" +
      "nt.Action\"u\n\027ListBreakpointsResponse\022A\n\013" +
      "breakpoints\030\001 \003(\0132,.google.devtools.clou" +
      "ddebugger.v2.Breakpoint\022\027\n\017next_wait_tok" +
      "en\030\002 \001(\t\"Y\n\024ListDebuggeesRequest\022\017\n\007proj",
      "ect\030\002 \001(\t\022\030\n\020include_inactive\030\003 \001(\010\022\026\n\016c" +
      "lient_version\030\004 \001(\t\"V\n\025ListDebuggeesResp" +
      "onse\022=\n\tdebuggees\030\001 \003(\0132*.google.devtool" +
      "s.clouddebugger.v2.Debuggee2\275\007\n\tDebugger" +
      "2\022\312\001\n\rSetBreakpoint\0226.google.devtools.cl" +
      "ouddebugger.v2.SetBreakpointRequest\0327.go" +
      "ogle.devtools.clouddebugger.v2.SetBreakp" +
      "ointResponse\"H\202\323\344\223\002B\"4/v2/debugger/debug" +
      "gees/{debuggee_id}/breakpoints/set:\nbrea" +
      "kpoint\022\312\001\n\rGetBreakpoint\0226.google.devtoo",
      "ls.clouddebugger.v2.GetBreakpointRequest" +
      "\0327.google.devtools.clouddebugger.v2.GetB" +
      "reakpointResponse\"H\202\323\344\223\002B\022@/v2/debugger/" +
      "debuggees/{debuggee_id}/breakpoints/{bre" +
      "akpoint_id}\022\257\001\n\020DeleteBreakpoint\0229.googl" +
      "e.devtools.clouddebugger.v2.DeleteBreakp" +
      "ointRequest\032\026.google.protobuf.Empty\"H\202\323\344" +
      "\223\002B*@/v2/debugger/debuggees/{debuggee_id" +
      "}/breakpoints/{breakpoint_id}\022\300\001\n\017ListBr" +
      "eakpoints\0228.google.devtools.clouddebugge",
      "r.v2.ListBreakpointsRequest\0329.google.dev" +
      "tools.clouddebugger.v2.ListBreakpointsRe" +
      "sponse\"8\202\323\344\223\0022\0220/v2/debugger/debuggees/{" +
      "debuggee_id}/breakpoints\022\240\001\n\rListDebugge" +
      "es\0226.google.devtools.clouddebugger.v2.Li" +
      "stDebuggeesRequest\0327.google.devtools.clo" +
      "uddebugger.v2.ListDebuggeesResponse\"\036\202\323\344" +
      "\223\002\030\022\026/v2/debugger/debuggeesB\206\001\n$com.goog" +
      "le.devtools.clouddebugger.v2B\rDebuggerPr" +
      "otoP\001ZMgoogle.golang.org/genproto/google",
      "apis/devtools/clouddebugger/v2;clouddebu" +
      "ggerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.devtools.clouddebugger.v2.DataProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_google_devtools_clouddebugger_v2_SetBreakpointRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_devtools_clouddebugger_v2_SetBreakpointRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_SetBreakpointRequest_descriptor,
        new java.lang.String[] { "DebuggeeId", "Breakpoint", "ClientVersion", });
    internal_static_google_devtools_clouddebugger_v2_SetBreakpointResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_devtools_clouddebugger_v2_SetBreakpointResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_SetBreakpointResponse_descriptor,
        new java.lang.String[] { "Breakpoint", });
    internal_static_google_devtools_clouddebugger_v2_GetBreakpointRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_devtools_clouddebugger_v2_GetBreakpointRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_GetBreakpointRequest_descriptor,
        new java.lang.String[] { "DebuggeeId", "BreakpointId", "ClientVersion", });
    internal_static_google_devtools_clouddebugger_v2_GetBreakpointResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_devtools_clouddebugger_v2_GetBreakpointResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_GetBreakpointResponse_descriptor,
        new java.lang.String[] { "Breakpoint", });
    internal_static_google_devtools_clouddebugger_v2_DeleteBreakpointRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_devtools_clouddebugger_v2_DeleteBreakpointRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_DeleteBreakpointRequest_descriptor,
        new java.lang.String[] { "DebuggeeId", "BreakpointId", "ClientVersion", });
    internal_static_google_devtools_clouddebugger_v2_ListBreakpointsRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_devtools_clouddebugger_v2_ListBreakpointsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_ListBreakpointsRequest_descriptor,
        new java.lang.String[] { "DebuggeeId", "IncludeAllUsers", "IncludeInactive", "Action", "StripResults", "WaitToken", "ClientVersion", });
    internal_static_google_devtools_clouddebugger_v2_ListBreakpointsRequest_BreakpointActionValue_descriptor =
      internal_static_google_devtools_clouddebugger_v2_ListBreakpointsRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_clouddebugger_v2_ListBreakpointsRequest_BreakpointActionValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_ListBreakpointsRequest_BreakpointActionValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_devtools_clouddebugger_v2_ListBreakpointsResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_devtools_clouddebugger_v2_ListBreakpointsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_ListBreakpointsResponse_descriptor,
        new java.lang.String[] { "Breakpoints", "NextWaitToken", });
    internal_static_google_devtools_clouddebugger_v2_ListDebuggeesRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_devtools_clouddebugger_v2_ListDebuggeesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_ListDebuggeesRequest_descriptor,
        new java.lang.String[] { "Project", "IncludeInactive", "ClientVersion", });
    internal_static_google_devtools_clouddebugger_v2_ListDebuggeesResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_devtools_clouddebugger_v2_ListDebuggeesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_clouddebugger_v2_ListDebuggeesResponse_descriptor,
        new java.lang.String[] { "Debuggees", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.devtools.clouddebugger.v2.DataProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
