// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/clouddebugger/v2/debugger.proto

package com.google.devtools.clouddebugger.v2;

public interface SetBreakpointRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.clouddebugger.v2.SetBreakpointRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the debuggee where the breakpoint is to be set.
   * </pre>
   *
   * <code>string debuggee_id = 1;</code>
   */
  java.lang.String getDebuggeeId();
  /**
   * <pre>
   * ID of the debuggee where the breakpoint is to be set.
   * </pre>
   *
   * <code>string debuggee_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getDebuggeeIdBytes();

  /**
   * <pre>
   * Breakpoint specification to set.
   * The field 'location' of the breakpoint must be set.
   * </pre>
   *
   * <code>.google.devtools.clouddebugger.v2.Breakpoint breakpoint = 2;</code>
   */
  boolean hasBreakpoint();
  /**
   * <pre>
   * Breakpoint specification to set.
   * The field 'location' of the breakpoint must be set.
   * </pre>
   *
   * <code>.google.devtools.clouddebugger.v2.Breakpoint breakpoint = 2;</code>
   */
  com.google.devtools.clouddebugger.v2.Breakpoint getBreakpoint();
  /**
   * <pre>
   * Breakpoint specification to set.
   * The field 'location' of the breakpoint must be set.
   * </pre>
   *
   * <code>.google.devtools.clouddebugger.v2.Breakpoint breakpoint = 2;</code>
   */
  com.google.devtools.clouddebugger.v2.BreakpointOrBuilder getBreakpointOrBuilder();

  /**
   * <pre>
   * The client version making the call.
   * Following: `domain/type/version` (e.g., `google.com/intellij/v1`).
   * </pre>
   *
   * <code>string client_version = 4;</code>
   */
  java.lang.String getClientVersion();
  /**
   * <pre>
   * The client version making the call.
   * Following: `domain/type/version` (e.g., `google.com/intellij/v1`).
   * </pre>
   *
   * <code>string client_version = 4;</code>
   */
  com.google.protobuf.ByteString
      getClientVersionBytes();
}
